### ISSUE TITLE
Cache storage query

### ISSUE THREAD

**Issue by gregLibert** [massalabs/thyra#102]
The storage doesn't cache information: if a web site is composed of index.html, style.css and script.js files, 3 calls are made to the blockchain.
Adding a local cache storage, temporary or not, will naturaly improve performance by reducing calls to the node and extactions of the same data.

**Comment by gregLibert** [comment]
This is something that can be done after storage pluginisation, but keep in mind that this can have a huge impact on big websites...

**Comment by SlnPons** [comment]
@gregLibert "it can have huge impact on big websites" - in which sense? 
If we reduce the # of calls by using cache storage, big websites upload will be longer. is that correct?

**Comment by gregLibert** [comment]
> @gregLibert "it can have huge impact on big websites" - in which sense? If we reduce the # of calls by using cache storage, big websites upload will be longer. is that correct?

No, it's about the get, not the push.

Right now when we fetch a website, we don't keep the local archive. This means that if you need to get 3 files from the same archive, Thyra will fetch the archive 3 times.
A classic website is composed of many files. In that case Thyra will fetch many times the archive...
