### ISSUE TITLE
Create a wiki explaining the installation process

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/thyra#108]
For now, the installation process is explained in the [README](https://github.com/massalabs/thyra/blob/451c8a663ab46511023dd94687a1a4165aed8197/README.md) of the project. But this README needs to be improved to give more details about the installation process and to fix the installation on MacOS with Apple Silicon. Since the installation process is pretty short and simple for now, but might get bigger and bigger due to the number of possible installation process (automatic or manual, Linux distribution specifics steps...). 

That's why it was decided to:
- [x] rewrite the MacOS installation part
- [x] rewrite the Linux installation part
- [x] move the installation process to the Github Wiki
- [x] Replace the installation parts in the README by links to the different wiki pages

This will make the README file shorter, and so, easier to read, and also allow us to simply expand the wiki when needed.

**Comment by SlnPons** [comment]
@thomas-senechal where have you posted the md file? Can you we close this issue please?

**Comment by thomas-senechal** [comment]
> where have you posted the md file? Can you we close this issue please?
I pushed everything in the linked PR (https://github.com/massalabs/thyra/pull/114). Once the PR merged, this issue will be closed automatically. So it should be closed once @gregLibert review and merge the PR.
