### ISSUE TITLE
Create a wiki for the .zip file format

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#110]
As a user, I want to know how my file should be formatted so it will be properly uploaded.
1. Write a step-by-step explanations (if possible) - mostly to explain that the 1st file needs to be the .html
2. Below the "import from" button, add the text: "Format info" with the same font and aligned that Website name message.
3. Add the wiki link to this text: on click it opens a new page

**Comment by SlnPons** [comment]
Just one small spelling mistake I think: at the very end "must contain an index.html file _AS_ a root.
<img width="897" alt="image" src="https://user-images.githubusercontent.com/109611779/191540872-47446dd2-f7aa-4148-adfa-c95d6f81164c.png">

**Comment by SlnPons** [comment]
@SebastienValla can you have a look at this wiki please? as we discussed it together.

**Comment by Thykof** [comment]
good catch, I have corrected with: This archive must contain a index.html file at the root
