### ISSUE TITLE
Add additional send operation commands

### ISSUE THREAD

**Issue by gregLibert** [massalabs/thyra#12]
Using the [same approach](https://github.com/massalabs/thyra/blob/main/pkg/node/sendoperation/callsc/callsc.go) defined to CallSC, add the other [send operation commands](https://massa.readthedocs.io/en/latest/technical-doc/api.html#send-operations):
- Transaction
- RollBuy
- RollSell
- ExecuteSC

**Comment by jwmdev** [comment]
Completed -  pull request merged:  Add additional send operation commands #28
