### ISSUE TITLE
[BACK] - GET websites name from dsnContract

### ISSUE THREAD

**Issue by Trottoir** [massalabs/thyra#128]
Modify `swagger.yaml` to create a new GET endpoint.

This endpoint will returns all websites key ( and relative data ) from the dnsContract.

We'll need to use the `get_addresses` RPC endpoint.

```
{
    "jsonrpc": "2.0",
    "method": "get_addresses",
    "params": [["A12jkDPTcdhkqGg9VoKsTwvkBwZeSHQw7wJqQYKrNesKnjnGejuR"]],
    "id": 0
}
```
Data will be retrieved by default like that : 
Latest uploaded at the beginning of the array, latest uploaded to be determined with create timestamp.

NO FILTER TO IMPLEMENT ATM

**Comment by Thykof** [comment]
result example:

```
{
	created_at: "2022-09-27",
	name: "app",
	address: "A1263WYRHvSZsEHtamdpN7TDZTKbRqokJUPrPgDph9EpJXAXscBy"
}
```
