### ISSUE TITLE
[SC] - Add attributes in websiteDeployer contract

### ISSUE THREAD

**Issue by Trottoir** [massalabs/thyra#129]
For referencing websites onchain, we need new data attibutes related to each `websiteDeployer` contract.

Add attibutes : 
-  Creation timestamp => uint
-  Update timestamp => uint

**Comment by SlnPons** [comment]
Hey @Thykof is this issue still relevant? 
I'm asking you because I understood that the SC websiteDeployer has been standardise to a more generic deployer. If I understood wrongly, please ignore this comment.

**Comment by Thykof** [comment]
We already implemented this https://github.com/massalabs/massa-sc-contracts/blob/main/assembly/website-deployer/websiteDeployer.ts#L132
