### ISSUE TITLE
[BACK] JS library: Expose Thyra's API for users to be able to sign a transaction from a dApp running on Massa 

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/thyra#134]
Where do we put the code for the library ?

The JS/TS library who will expose Thyra's API must take into account the following :
  - The library should take into account that Thyra may want to communicate with other blockchains in the future => Creates an 
  abstraction layer
  - The library should expose the ability to sign a transaction

**Comment by SlnPons** [comment]
@gregLibert is this issue still relevant with current state of Thyra?

**Comment by gregLibert** [comment]
@SlnPons @ASAPSegfault Are you looking for [this endpoint](https://github.com/massalabs/thyra-plugin-wallet/blob/811ad3252b09b595c9de1e17650439ae361a4955/api/wallet_api-v0.yml#L192-L232)

**Comment by ASAPSegfault** [comment]
Yep that's it, this issue is now irrelevant
