### ISSUE TITLE
[BACK] - Send callSC operation endpoint creation

### ISSUE THREAD

**Issue by Trottoir** [massalabs/thyra#137]
Create a POST endpoint that will handle `callSc` ONLY.

Modify the swagger.yaml file in order to handle the sendOperation request already implemented in `callsc`

```
	MaxGaz          int64       `json:"max_gas"`
	GazPrice        string      `json:"gas_price"`
	ParallelCoins   string      `json:"parallel_coins"`
	SequentialCoins string      `json:"sequential_coins"`
```
will have default value, can be overrided if specified
```
	TargetAddr      string      `json:"target_addr"`
	TargetFunc      string      `json:"target_func"`
	Param           interface{} `json:"param"`
```
will be defined by API caller

Don't foget to integrate the password retriaval in the GUI secret input.

**Comment by thomas-senechal** [comment]
We just noticed that an API call doing what we wants already exist [here](https://github.com/massalabs/thyra/blob/45a836e21a5d24731b3d7e0eb0ad664e212ee49b/int/api/cmd/execute_function.go). We just need to update it to use the new tools we recently built such as the new wallet handling and make sure it's working as expected.
