### ISSUE TITLE
 2-step confirmation on delete-wallet action

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/thyra#146]
This is a suggestion from a User perspective on Wallet lists on Thyra:

**Steps to reproduce:**

1. Created a wallet.
2. It appeared on the right side of the screen in the Wallet list.
3. Clicked on 'X' 
4. It deleted my wallet from the list. 

**Solution:**
We should require a confirmation, after clicking on 'X'. Just a simple 'Are you sure you want to delete the wallet from the list?', modal window should do. 

P.S. This is to keep in mind for the future. Wallets that'll have a non-zero balance, once deleted from the list might be very hard to add later.

**Comment by SlnPons** [comment]
Adding context and info on top of this issue that we need to address to open Thyra to all: 
**Context** 
Today, one single click is sufficient to delete your wallet on the 'Wallet' page. 
This is too dangerous as deleting your wallet will make you lose your Massa but will also prevent you from editing your website in the future. 
Adding a 2-steps to make sure users don't click there by mistake sounds legit. 

**Need**
*Create a "Are you sure" pop-up to explain the consequences of deleting a Massa wallet
*Make sure to delete the wallet from the directory if the user click 'yes'

**User flow**
End user goes to the 'Wallet' page 
End user clicks on the 'X' to delete a wallet 
End user sees a pop-up coming from Thyra on their device and can either confirm the delation or cancel it
End user can't see their wallet on the list anymore

**How to**
*Create a pop-up using the same GUI as the password - /!\ if and only if it's also compatible on mobile - see https://github.com/massalabs/thyra/issues/199
*Add following message and explanation:
Main message: "Delete wallet <xxxxx>"?
Sub message: "If you delete a wallet, you will MAS associated to it and won't be able to edit websites linked to this wallet anymore"
Buttons: "Delete" and "Cancel"

**Technical details**
TO BE ADDED

**Comment by Thykof** [comment]
`/!\ if and only if it's also compatible on mobile - see https://github.com/massalabs/thyra/issues/199`

Fyne GUI library that we use for Thyra desktop is compatible on mobile devices, you can download from the stores the demo app. But we have not chose yet the technical stack for Thyra Mobile and it may be different (flutter, react native...), we might need an ADR on this
