### ISSUE TITLE
[Bug] Errors while trying to upload a website with the correct wallet password

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/thyra#148]
**Goal:**
I wanted to upload a website via Thyra.

**Steps to reproduce:**

1. Started uploading the wallet
2. Got asked to Enter my password -> Entered the correct one.
3. Clicked on the 'Call' button
4. Got 2 error messages: I 'undefined' error message.
5. After repeating the step 2) and 3) a few times, got the error message II 'Error while fetching DNS owned'.

**Comment by SlnPons** [comment]
@Trottoir here is the latest version of the error messages to push (just made some modifications thanks to Ena eyes)
```
[‘Wallet-0001', ’That wallet name is taken. Try Another’],
    ['Wallet-0002', ‘Wrong password. Try again’],
    ['Wallet-0003', ‘Error while retrieving that wallet. Try again’],
    ['Wallet-1001', ‘Enter a wallet password’],
    ['Wallet-1002', ‘Enter a wallet name’],
    ['Wallet-1003', ‘Error while creating your wallet. Try again’],
    ['Wallet-2001', ‘Select a wallet to delete’],
    ['Wallet-2002', ‘Couldn’t delete the wallet. Close all programs which use this wallet and try again’ ],
    ['Wallet-3001', ‘Error while importing this wallet. Try again’],
    ['Wallet-4001', ‘Couldn’t connect your wallets. Reconnect all your wallets and try again’],

    ['Domains-1001', ‘Error while looking for your domain names’],
    ['Domains-1002', ‘Error while connecting your domain and smart contract’s address’],

    ['WebCreator-0001', ‘Error while creating the website container’],
    ['WebCreator-0002', ’Couldn’t read the ZIP file. Try again’],
    ['WebCreator-0003', ‘ZIP-file upload failed. Try again’]
```

**Comment by SlnPons** [comment]
Closing this bug as I think it's the same as this one: https://github.com/massalabs/thyra/issues/166
Let's say you type the wrong password once, and try again with the correct one you experience exactly the same thing as just described above.
