### ISSUE TITLE
Error library - Update vocabulary and add to the library

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#167]
The error "DnsName already occupied" should: 
* be added to the error library 
* should be "That website name is already taken. Try another."

**Comment by thomas-senechal** [comment]
After discussing with @SebastienValla and he explained me that this error message is in [massalabs/massa-examples-deployer](https://github.com/massalabs/massa-examples-deployer), [here](https://github.com/massalabs/massa-examples-deployer/blob/main/contracts/dns/dns.ts#L33). 
I will create an issue in [massalabs/massa-examples-deployer](https://github.com/massalabs/massa-examples-deployer) to implement that fix.
