### ISSUE TITLE
MacOS - Add checks in the installation script

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/thyra#173]
In https://github.com/massalabs/thyra/issues/172, an basic installation script will be created. This installation script doesn't do any checks and might break users device configurations. We need to add some checks in the script to ensure that we need, or not, to run some specific steps. This should make the installation process more secure for the users.

**Comment by Thykof** [comment]
@gregLibert and @SlnPons does this merged PR close this issue https://github.com/massalabs/thyra/pull/176 ?

**Comment by thomas-senechal** [comment]
> @gregLibert and @SlnPons does this merged PR close this issue https://github.com/massalabs/thyra/pull/176 ?

As [I mentioned](https://github.com/massalabs/thyra/pull/176#issuecomment-1270210729) in https://github.com/massalabs/thyra/pull/176 , I think we can close this issue since it has been implemented.
