### ISSUE TITLE
Signature API - Prep' email with Tech info to connect

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#177]
Send by: PM
To: Dusa team (Tech people)
Objectives: 
* Describe the process (step-by-step) to follow for them to be able to connect their app to the created end-point to sign transactions. 
* Give an exemple if you think it's easier
* Use curl (to keep it as much simple as we can)

**Comment by Thykof** [comment]
I have written a wiki here that explain how to interact with Massa blockchain through a decentralized website: https://github.com/massalabs/thyra/wiki/How-to-develop-DApp-on-Massa

**Comment by SlnPons** [comment]
Not sure they are important comments as I'm not the audience of this wiki, I'll let you judge. But here are some comments: 
1 - Deploy Dapp = website + SC?
`With Thyra web on chain, you can deploy decentralized applications:

*deploy website through Thyra web on chain (https://github.com/massalabs/thyra#-web-on-chain)
*deploy smart contracts`
-> the way it's written I understand that it's deploying a dapp is about deploying website and SC.

2 - Replace by what?
`(dont forget to replace full_path_to_thyra)`

**Comment by Thykof** [comment]
1. Yes, a decentralized application can be composed of a front end website and one or more smart contract.
2. I have clarified the sentence.
