### ISSUE TITLE
BUG - When launching Thyra, accessing a warning page

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#178]
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/109611779/194291527-fd1bba43-6015-44be-8814-084645a18de4.png">

**Comment by SlnPons** [comment]
**Context** 
This is due to the https certificate that is not natively integrated to Thyra. This error will quickly become problematic as soon as we'll add wallet / crypto app or transactions in Thyra. 
It would be good to start identifying how we can handle this nicely. 

**Needs**
Install https certificate on Thyra during the installation process 

**User journey**
End user installs Thyra on their device
End user opens their default browser 
End user types my.massa/thyra/wallet and is redirected to https://my.massa/thyra/wallet/index.html directly without seeing the screenshot above.

**How to** 
* Identify how we can install the https certificate during the installation process 
* Make sure we have a solution for all OS identified in the DoD as well as all browsers (if not, list the identified blockers for each)
* Try to implement at best; or to explain the process to do it at least. 

**Technical details**
TO BE ADDED

**Comment by SlnPons** [comment]
Potentially linked to this issue: https://github.com/massalabs/thyra/issues/154

**Comment by thomas-senechal** [comment]
In the picture in the description, we can see that the CSS isn't applied on the html page. This could be related to https://github.com/massalabs/thyra/issues/203 that has been resolved, but in https://github.com/massalabs/thyra/issues/203, the bug seemed to only applied to `.js` files, and after testing a bit, `.css` files seemed to always have `text/css` MIME type. I tried to reproduce the bug thanks to @SlnPons informations, but couldn't reproduce it, neither with commits prior to https://github.com/massalabs/thyra/issues/203 merge, nor with [current main version](https://github.com/massalabs/thyra).

We can assume that this bug has been fixed, either by https://github.com/massalabs/thyra/issues/203 or another merge. 
@SlnPons I think we can close this issue for now, and reopen it if the bug reappears. What do you think about that ?

**Comment by SlnPons** [comment]
I can't reproduce it consistently on my side either. I will close this issue, but @gregLibert I remember you said it may be linked to the https certificate. If so, could you share with us your insights to see if we should spend more time on it please? 

In the mean time, issue closed.
