### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#179]
**Steps to reproduce:**
Downloaded a new arm64 binary for the latest release -> when trying to initialize Thyra (after entering the folder of the file), new macOS gives the warning:
'macOS cannot verify that this app is free from malware.'

As a non-dev user, I am uncertain what to do next. 

**Solution:** 
Update the Wiki for the Installation in Thyra repository with a message like:

" If you received a warning message from your macOS saying 'macOS cannot verify that this app is free from malware':
1. Using Finder, go to the folder where you downloaded the binary. 
2. Open the downloaded binary file with a double-click or tap. 
3. Close the terminal window that was opened after the previous step. 
4. In the existing terminal, run the command: ./thyra-server_darwin_arm64 "

To reconfirm that the suggested message is correct, please contact Thomas, he saw the process.

![Image](https://user-images.githubusercontent.com/113043914/194116647-8b566bee-fcd2-48bc-a5cc-39adfc4055f3.png)

**Comment by SlnPons** [comment]
Shared by Nathan - how to sign an app tutorial: https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development

**Comment by SlnPons** [comment]
@Thykof sorry, I'm a bit confused with the installation script for macOS. 
Today, we have one (here: https://github.com/massalabs/thyra/pull/176). When using this installation script, do we have this error again? 
So that I know how to prioritise this issue. Cheers

**Comment by Thykof** [comment]
@SlnPons no, with the current installation script for macos, there is not any problem with unidentified developer.

**Comment by SlnPons** [comment]
Closing this issue as the installation script prevent it from happening.
