### ISSUE TITLE
Increase website size upload limit 

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#196]
**Context** 
A website size upload limit has been added to avoid having super heavy website uploaded on Massa blockchain during the user test#1 that could have caused robustness problem and infinite calls that we were not testing.

This limit is arbitrary and should not exist. The fees will naturally fix limits.

**Need** 
Remove this size limit so that end-user will be able to push what they want.
* Remove the size limit in the back-end
* Remove the size limit in the front-end

**User journey** 
1. End user run Thyra and go to the website page
2. End user upload a website of any size 
3. Upload is successful and end user can see it.

**How to**
* Remove the size limit in the back-end
* Remove the size limit in the front-end

**Comment by SebastienValla** [comment]
After discussion with @SlnPons  we just increase the size to 4 Mo to not erase the size limitation feature if needed in future
