### ISSUE TITLE
[Potential known BUG] - Thyra windows installer

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/thyra#201]
As of now, the script set up DNS only for connected network adapters, which means : 
- If someone run the script with Wi-Fi and Ethernet connected on their device, then Thyra will always works.
- If someone run the script with Wi-Fi OR Ethernet only and then later switch to the other, Thyra will not work (because the DNS has been set only for the connected network adapter at the moment the script was launched)

The problem being that if we force the DNS setup on all network adapters, connected or not, it may potentially break stuff on the user computer.

**Comment by thomas-senechal** [comment]
Should already be resolved [here](https://github.com/massalabs/thyra/blob/6fc6cdb2c85b81c50f72f09589c70f89bee51b55/scripts/windows_installer.py#L62).
