### ISSUE TITLE
Prevent .zip file to be uploaded if no index.html at root

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#209]
**Context** 
As soon as you select a zip file, the event manager starts the container deployment and so the process start even though the format is not correct and so the file won't open once the upload is finished.
It would be great to add a step to verify that the file has the correct root ('index.html' at the root) in order to prevent end users to upload (and so spend money) for nothing. 

**Need**
* Once the file is selected, inspect it to validate that zip has the 'index.html' at the root
* If the format is correct, start the upload
* If the format is not correct, then display a clear error message

**User flow**
End user installs and run Thyra 
End user has a wallet and goes to the 'Websites' page
End user selects their websites using the 'import from' button 
End user sees an error message if the file format isn't correct / if the file is correct, end user sees the upload module starting the upload

**How to** 
* Inspect the selected file 
* Add the error message created to the error library following the same standard

**Comment by 0xMazout** [comment]
I really think parsing the zip file , in front side is not a good practice and a good idea to do it in JS ( if it's possible).

But what i can propose is to make this control on the backend side. User click on deploy.
Before starting all of the process to upload Website. We can dezip file and parse file to search index.html.

If File is not present we came back to last screen with an error
If File is present then continue the other processes

**Comment by SlnPons** [comment]
@0xMazout My main and only objective is to prevent the user from spending money if the file hasn't the correct format (index.html at the root). 
So either we do that in front-end or back-end, I don't care. However, clicking on 'Deploy' implies a lot of different calls which I'm not sure can be managed differently (password GUI, Container creation...) at this stage. When I say this stage I mean knowing that we don't want to rebuild the event manager nor UX now. We will review and potentially rebuild these objects when we will transform the web on-chain in plug-in.
I hope it's clear, don't hesitate to call me ;)
