### ISSUE TITLE
Thyra as an API gateway

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#228]
**Context**
See details[ here](https://www.notion.so/massa-innoteam/Plug-ins-in-Thyra-2c17c0f694e943c48555bb705fab5453). 
But in short, moving Thyra into a modular architecture ables to support plug-ins is a strategic move for this product. To do so, we'll add the SC playground and simulator functionality to Thyra using plug-in to start with.

**Needs** 
* Try for 2 days with this investigation to go as far as you can with this idea of Thyra as a plug-in
* Address the must have listed below in the 'how to' section
* If you make important technical decision, please make sure to share it with PM and/or to write document about it for keep the context clear.

**How to** 
1. Enable Thyra

- [ ] Thyra starts plugins with there manifest.json
- [ ] a plugin is an HTTP REST API, a binary
- [ ] Thyra is an API gateway, it forwards requests to the right plugin
- [ ] Thyra do the routing with the URL path prefix which is the name of the plugin
- [ ] Plugins do not know other plugin host and port, Thyra does
- [ ] Write simple but usable documentation in Notion so that all builders can use Thyra endpoints to create their own plugins during the hackathon.

2. Add existing simulator

- [ ] thyra endpoint: /simulator/simulate
- [ ] plugin endpoint: /simulate
- [ ] API that require a json in the request body, return the trace.json in the response body
- [ ] run the simulation with the input json

**Technical details**
To be added

**Comment by 0xMazout** [comment]
We are working on it With @peterjah 

The goals at this moment are : 
- Playgrounds integration
- Simulator integration
- Api to communicate between Simulator and playgrounds through Thyra

**Comment by 0xMazout** [comment]
Updating Playground : 

-Add control on export Compile func , Needs to have a compiled file once time , if not Compile the actual code
-UserFlow input : user : Click on Simulate -> process : Compile -> user : Choose File Input Config || process Export Compiled Files (WASM) --> Send WASM File and Json if both of process are sucess 
- Result Display : Ledger.json and Trace.json Still analyzing what is pertinent to display without causing big changes in ui

**Comment by 0xMazout** [comment]
Creation of three issues after the brain-storm : 
https://github.com/massalabs/massa-sc-playground/issues/42
https://github.com/massalabs/thyra-playground-plugin/issues/2
https://github.com/massalabs/thyra/issues/235
