### ISSUE TITLE
Thyra app on desktop after installation

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#233]
**Context** 
Thyra can now be installed on desktop thanks to installation script. To fully finish this part and enable everyone to install and run Thyra easily, there is one last step to achieve: adding Thyra as an app on user's desktop.

**Need** 
To create a Thyra app interface that will only enable the user to active / desactivate Thyra. See attached screenshots
To cover the 3 OS identified in the[ DoD](https://www.notion.so/massa-innoteam/Stream-1-Function-Process-4b809e6716e94c6085c9e6cefe832140#979b66ba544c4ef3848c29d1a9d9a2af)
<img width="618" alt="image" src="https://user-images.githubusercontent.com/109611779/198046253-1d942f1b-c120-4b9d-af9c-51d3992e4669.png">

**How to** 
* Create .dmg for macOS (and linux and windows equivalent) to install Thyra 
* Add Massa logo to desktop panel control to allow user to active / desactivate Thyra (see attached screenshot)
* Add link to Thyra home page (currently: http://my.massa/thyra/wallet/index.html) 

**Technical details** 
To be added prior to start the work. Ping me if you think we need to break down this issue per OS.

**Comment by B-Naoufal** [comment]
A first Version of Thyra App has been developed, more tickets will be opened to add some specific functionalities :  
https://github.com/massalabs/Thyra-Menu-Bar-App

**Comment by gregLibert** [comment]
@B-Naoufal can you link the PR to this issue ?

**Comment by B-Naoufal** [comment]
@gregLibert here is the Repo link no PR : https://github.com/massalabs/Thyra-Menu-Bar-App

**Comment by peterjah** [comment]
nice work!

**Comment by Thykof** [comment]
My review: 
- in `background_process.py`, I think you don't need `self.pid` because you can access is with `self.process.pid`
- in `background_process.py`, line 14 you can do `self.process = subp...` you don't need `proc` variable
- in `thyra_app.py` line 12 you are duplicating 'thyra-server' variable, you can import is from `background_thyra_scripts` `CONST_CMD_THYRA`

**Comment by SlnPons** [comment]
@B-Naoufal the issue is in review KO for a long time I believe. What are the remaining comments to address? I don't see them...
