### ISSUE TITLE
Integrate playground plug-in to Thyra

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#235]
**Context**
For the playground to be integrated as a plug-in in Thyra, we need to integrate the different parts to existing Thyra so that user can interact with it.

**Needs**
Make the playground and simulator accessible in Thyra. 
Make the playground and simulator usable in Thyra. 

**How to**
- [ ] Launch front-end playground plug-in
- [ ] Process plug-in detection

**Comment by 0xMazout** [comment]
As I understand : 

The main target is to create an experimental process to :

- Host any plugin on Thyra ( Adding a Folder)
- Find a way to launch plugin ( Adding process to launch plugin )
- Adding to the frontend a way to access to the plugin ( Create button to display "WebPages"  )

It seems we have two types of Plug-in at this moment : 
-Web plugin , diplaying the index.html of the plugin
-API plugin,  made an Api available linked to a config file (endpoints exposed)


How ? 

Create folder to host plugin 
Create launch file standard (Typing , Launch procedure)
Create Launch process to read launch file

**Comment by 0xMazout** [comment]
At this moment the target is integrate playground and Playground API plugin into thyra 
- Add Playground 
- Add Playground API Plugin 
- Process to Launch Both 
- Add Landing Page to manage both plugins

**Comment by SlnPons** [comment]
Discussed w/ @peterjah :
* Impossible to access the playground plug-in. The playground page appears on Thyra once installed but I can't access it on port 8080.
Here is what I do step-by-step:
* on macOS 
* Install latest version of thyra using go install cmd 
* run thyra using thyra-server cmd 
* open my.massa/thyra page 
* see the playground tab 
* click on the playground plugin tab, see the attached screen
* 

![Image](https://user-images.githubusercontent.com/109611779/204541910-d4ea7388-e39f-47cb-886a-9730f7fb2e78.png)


* have the following info on my terminal 
```➜  ~ thyra-server
2022/11/29 14:24:01 Connected to node server https://test.massa.net/api/v2 (version TEST.16.1)
2022/11/29 14:24:01 Plugin Manager initialization
2022/11/29 14:24:01 Starting plugin 'Playground plugin' on port 4200
2022/11/29 14:24:01 Serving thyra server at http://[::]:80
warning: insecure HTTPS configuration.
	To fix this, use your own .crt and .key files using `--tls-certificate` and `--tls-key` flags
2022/11/29 14:24:01 Serving thyra server at https://[::]:443
Playground plugin: flag provided but not defined: -path
Playground plugin: Usage of /Users/slnpons/.config/thyra/plugins/playground-plugin/thyra-playground-plugin:
Playground plugin:   -port int
Playground plugin:     	set listening port (default 8080)```


I see different problems to be solved - not necessary in this issue: 
1. The installation process is too manual - improvement point for the future :) 
2. The default port is 8080 but the playground plug-in default config is on port 4200 - could we aligned this? same it's improvement for the future of the plug-in manager. Doesn't have to be done for this.
3. URL of the playground plug-in can be improved so it's more user friendly

**Comment by SlnPons** [comment]
Now done. The plug-in needed to be launched outside thyra for then to work with thyra. I missed this step and so couldn't access the plug-in. 
It's now done and tested. Thanks Naoufal for helping me out with this.
