### ISSUE TITLE
Bug - Installation script Windows system error 5

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#236]
**Describe the bug**
When using the existing Windows installation script, user has a system error on the terminal which prevent him/her to know if it's correctly installed.

**To Reproduce**
1. Go to https://github.com/massalabs/thyra/tree/main/scripts
2. Click on Thyra installer.bat and download it
3. Run it on your machine
4. See following error
```Accès refusé.
Accès refusé.
L’erreur système 5 s’est produite.

Accès refusé.

L’erreur système 5 s’est produite.

Accès refusé.

Installation and setup successfull
Appuyez sur une touche pour continuer...
```

**Expected behavior**
Once the installation is done, user should see an "Installation successful" message on the terminal.

**Thyra version**
Latest v0.0.7

**Desktop (please complete the following information):**
 - OS: Windows 10

IMPORTANT note: If the error described above is only due to the OS version, please don't try to correct now but create an issue to handle windows 10 better. 
Our DoD only covers Windows 11 atm so no need to work on Windows 10 as for now.

**Comment by ASAPSegfault** [comment]
I was able to reproduce the issue, you will solve it by executing the installer as an administrator.
I added a check for this in the associated PR at the very start of the script so that the program stops right away and the error that is printed is explicit now.
