### ISSUE TITLE
Bug - Linux installation scripts command not found error

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#237]
**Describe the bug**
When using the existing linux script, user has an error 'command not found' which prevent him/her from using Thyra.

**To Reproduce**
1. Go to https://github.com/massalabs/thyra/tree/main/scripts
2. Click on Linux _install.sh and download it
3. Run the downloaded file
4. See following error
```
./linux_install.sh: line 2: $'\r': command not found
./linux_install.sh: line 5: $'\r': command not found
./linux_install.sh: line 12: syntax error near unexpected token `$'{\r''
'/linux_install.sh: line 12: `architecture_version () {
```

**Expected behavior**
Installation scripts have been created for non-developer users, so when they click on the downloaded file it should install Thyra in a straightforward way and display an "installation successful" message on the terminal so users know it's ok. 

**Thyra version**
Latest v0.0.7

**Desktop (please complete the following information):**
 - OS: Ubuntu-20.04

**Comment by SlnPons** [comment]
Can't reproduce with above details. Need more info from user

**Comment by jimmylies** [comment]
This error appears when I try to run linux_installer.sh directly in the scripts folder after a git clone of the thyra repo.
It doesn't appear by dowloading the installer from this link: https://github.com/massalabs/thyra/tree/main/scripts

**Comment by peterjah** [comment]
do you confirm you use ubuntu ? what is your shell interpreter and what is the exact command you execute ?

**Comment by peterjah** [comment]
anyway if you are able to install Thyra by downloading the script and execute it, i think the issue does not comes from the install script itself

**Comment by SlnPons** [comment]
@peterjah yes, Thib uses ubuntu. The version is specify in the issue ;) 
But based on your comment, I'll close this issue. If we encounter the problem again, we'll create a new issue.
