### ISSUE TITLE
Implementing Local Linter to be the same as Github Actions [Dev-Process]

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/thyra#239]
Context
For Thyra and all of others repo, we need to create a local linter config to deploy on our VS.CODE matching with the Github Actions. 
This linter file is to avoid unecessary commit to fit with github actions rules post push

It's not a priority tasks but it needs to be done to speed our developements process.

At this moment devs lost times to match the local linter with the github actions linter.

Each time you push, if you are not aware of all the rules you have to make some adjustment to github action rules and push it.

If we can match the two linter we can avoid this adjustment post push

Goal 
Aligning Github Actions Rules with Local linter in the repo 

Needs
Lists of Github Actions 
Find a way to implement the Linter as a file in the repo

How to
??

**Comment by SlnPons** [comment]
Is it the same as: https://github.com/massalabs/thyra/issues/42 @0xMazout ? 
If yes, let's keep yours there is more details.

**Comment by SlnPons** [comment]
May be relevant, but potentially easily solved with removing local linter cache. 
Inconsistent behaviours noticed across the team on this topic (mostly on windows and linux)
