### ISSUE TITLE
Create a Feature issue template

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/thyra#255]
**Description**
Currently, we write issues entirely by hand, which makes issues that doesn't have the same information and that doesn't have the same format from an issue to another. Also, our users might want to create issues to request features. Without templates, it will lead us to having more issues that might miss some information to implement a feature. Which would be a waste of time. 

Having issue templates would save us a lot of time to make sure that all the information we need are present in the issues.

This feature template should communicate all the information the devs need to make the feature.

We could also have a template for the investigations, but I'm not sure it would be that useful since it's highly linked to features issues.

**Draft Templates**

```
**Description**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Needs**
A clear and concise description of what are the needs of the feature.

**Technical solutions**
A clear and concise description of any alternative solutions.

**Tasks**
A simple list of tasks to be done to implement the feature.
- [ ] 

**Additional context**
Add any other context or images about the feature request here.
```

**Technical**
I noticed that GitHub now allows us to create template as `.yml` that are then displayed in a nice UI. We could use that kind of template also to automaticaly add labels on an issue, for example, have a "Issue's Area" field with for example, "Website Deployment", "Installation", "Website Registry", "Wallets"... which would help us to filter issues. This `.yml` format also allows us to automaticaly add labels to issues based on the template used, for example, a "bug" template would be tagged as "bug".

**Comment by SlnPons** [comment]
Done in all repos using other tickets.
