### ISSUE TITLE
Add a --version option at launch

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/thyra#262]
**Context:**
Currently, Thyra doesn't have a `--version` option at launch. This means that when someone downloads and install Thyra using an installation script or using the release binaries, that person has no way to know which version is installed on its computer.

The version is only available in release titles. It would be great to have a way to store that version in Thyra to be able to display it using `--version` option.

**Todo:**
- [ ] Find a way to store the version in the binaries built by the [CD workflow](https://github.com/massalabs/thyra/blob/main/.github/workflows/CD.yml).
- [ ] Add a `--version` option that displays the version.

**Comment by SlnPons** [comment]
@thomas-senechal how can I test that without doing a new release?
