### ISSUE TITLE
Lack of documentation on launching thyra

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/thyra#265]
I followed this tutorial to install thyra : https://github.com/massalabs/thyra/blob/main/INSTALLATION.md#macos . I made the "automatic" part but there is no explanation on how to launch thyra after installing I had to check the script to see it has been move to `/usr/local/bin` to launch it.
cc @SlnPons

**Comment by SlnPons** [comment]
Thanks Auré! ;) 
I've updated the doc, can you check on confirm that it's ok? 
Or should I specify all the parth on the cmd?
