### ISSUE TITLE
Importing Massa client wallet in thyra

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/thyra#266]
Currently in Thyra there is a button to import wallet but it doesn't support the format of the `massa-client`. In the `massa-docs` it's written that people need to create a wallet with `massa-client` but after when they will use thyra they can't reuse the same wallet.

If they create both during the same day they can't have tokens on both from the faucet it can be a pain point in the hackathon

cc @SlnPons

**Comment by SlnPons** [comment]
Good point! Thanks for sharing. 
We'll address this issue later; in the mean time a workaround that I can suggest is: create a wallet via Thyra and send coins from your massa-client wallet to your thyra wallet.

**Comment by AurelienFT** [comment]
> Good point! Thanks for sharing. We'll address this issue later; in the mean time a workaround that I can suggest is: create a wallet via Thyra and send coins from your massa-client wallet to your thyra wallet.

I agree with this workaround but it should be documented for the hackathon i think.

**Comment by SlnPons** [comment]
Will work on a page to summarise all the normal-not-normal things like this. As soon as it's done will share it with all the hackathon team.
