### ISSUE TITLE
Replace generated keys by the wallet ones

### ISSUE THREAD

**Issue by Trottoir** [massalabs/thyra#27]
Replace Generated keys by the ones created in the `wallet`

https://github.com/massalabs/thyra/blob/1643ee3436ec7feef46ab82f103e8dfbe1049d62/cmd/callSC/main.go#L14

**Comment by gregLibert** [comment]
@Trottoir I think that this was solved by [222e6d6](https://github.com/massalabs/thyra/commit/222e6d69ae02046df764cecf55169ef91cffc20a).
