### ISSUE TITLE
Thyra installation on WSL ubuntu

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/thyra#276]
Someone during our GGH tried to launch Thyra on WSL ubuntu. The automatic installation throwed him : 

```
INFO: This installation script will install the last release of Thyra and will configure your local DNS to resolve .massa if needed. [sudo] password for loc: System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down [Linux]ERROR: dnsmasq service failed to restart
```

He made the manual one but as he wasn't able to open a web browser on it we couldn't see the result.

**Comment by thomas-senechal** [comment]
Closed in favor of https://github.com/massalabs/thyra/issues/466
