### ISSUE TITLE
Add formating tool in readme

### ISSUE THREAD

**Issue by Thykof** [massalabs/thyra#282]
Issue: Sometimes linter complain about gofumpt, it's a formatting tool 

Solution: Add a section in the readme file inspired by https://bluehive.medium.com/how-to-fix-file-is-not-gofumpt-ed-gofumpt-error-bca04d64229f

**Comment by thomas-senechal** [comment]
This has been already done. [See README](https://github.com/massalabs/thyra/blob/main/README.md#how-to-resolve-golangci-lint-recurring-errors-) 

I think we can close this issue unless you think some information are missing.

@Thykof @SlnPons
