### ISSUE TITLE
Plug-in manager for Wallet plug-in

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#284]
**Context**
We are going to isolate every object contained in Thyra so that we'll be able to pluggenised Thyra while improving these objects. 
To do so we need to address the object isolation task but also this task to assure that the end users will still be able to use the "plug-in" service and perform expected action. 
Here, we'll make sure that the plug-in 'wallet' as the exact same functionalities than the current wallet included in Thyra. 

**Needs**
* As a dev, I want to communicate with the Wallet plug-in to assure that the basic functions are still up and running.
* As a PM, I want the plug-in manager to be able to detect if the wallet plug-in is present / active.
* As a user, I want to be able to manually* installed the wallet plug-in on Thyra and perform following actions as now:
Create a wallet 
Read a wallet
Delete a wallet
Sign a tx

*manually installed = not necesserary in 1-click only. It can be using cli. What ever is simpler for now.

**How to** 
- [ ] Connect Thyra API to the wallet plug-in API 
- [ ] Connect Thyra front-end to wallet plug-in front-end: make sure that the URL is: my.massa/thyra/name_of_the_author/name_of_the_plugin (here it should be: my.massa/thyra/massalabs/wallet)

**Technical details**
*phase 1:*
  - ~Wallet plugin should be added in plugin dir by the install script.~ to be done later
  - Thyra will start the plugin at launch (this work is probably already done)
  - The wallet plugin should work in parrallel of the actual wallet
*phase 2:*
  - ~All code that use the wallet (sign+send transaction?) must use the the plugin and specifically the new endpoint created for this purpose.~  to be done later
*phase 3:*
  - ~delete all code related to wallet in thyra ~ to be done later

**Comment by B-Naoufal** [comment]
everything is covered in https://github.com/massalabs/thyra-plugin-wallet/issues/11 , and https://github.com/massalabs/thyra-plugin-wallet/pull/13 , except ~delete all code related to wallet in thyra ~ to be done later will be postponed for the moment , this issue will be closed once the 2 mentionned PRs are merged , and passed QA Review  @SlnPons

**Comment by SlnPons** [comment]
Super, thanks Naoufal! 
As discussed, I will then close this issue as https://github.com/massalabs/thyra-plugin-wallet/issues/11 , and https://github.com/massalabs/thyra-plugin-wallet/pull/13 covered it & create another issue in thyra-plugin-wallet to delete the code related to thyra. 
Cheers.
