### ISSUE TITLE
Add Website timestamp on frontend registry page

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/thyra#285]
Context
With args modification the way to catch website timestamp has changed. As args is not available yet in vanilla JS, we decided to remove the timestamp from the website registry for the moment.

Needs

As a user I want to see when my website has been uploaded and see the oldest websites on massa.

How to
Add a column to display website timestamp
Display timestamp on DD-MM-YYYY format

Technical details
to be added

**Comment by SlnPons** [comment]
Not a priority as the registry would probably be revamping. So closing it for now to avoid doublon.
