### ISSUE TITLE
Hardcode the DNS addresses in the code and create a flag for handling multiple DNS

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/thyra#287]
**Context :**
As of today we offer the node-server flag to users for them to connect Thyra to various environments (Innonet, testnet, labnet, custom network).
The problem being that Thyra has to know which SC addresses it needs to communicate with in order to work, an information that is present only for the Innonet network as of now.

**Needs**
- Allow Thyra user to communicate with the right DNS address accordingly to the node-server flag that he passes to Thyra.

**How to** :
- Select DNS address (hardcode it in server.go for now) based on which network we are on
- Update DNSRawAddress in dns.go for it to match the chosen DNS address
- Create a flag to pass a custom DNS address. Note that if this flag is passed by the user, it should always take precedence over values in the code.

**Comment by SlnPons** [comment]
@thomas-senechal what do you think about adding a step to the existing procedure to "create a new innonet" to ask the team to add the new addresses to the code? 
Like this we don't forget.

**Comment by SlnPons** [comment]
Can you add it please? I won't be able to specify where in the code we should do it 😇

**Comment by SlnPons** [comment]
Added in this ticket to be done: https://github.com/massalabs/thyra/issues/390
