### ISSUE TITLE
Add onchain website surfing howto

### ISSUE THREAD

**Issue by gregLibert** [massalabs/thyra#3]
Add documentation on how to browse website stored in the blockchain. This should include:
- how to run thyra-server
- how to display a website stored in the testnet

**Comment by SlnPons** [comment]
@gregLibert with the latest update of the README, do you think we can close this issue? 
Knowing that the idea will be to facilitate viewers access to massa websites naturally thx to UX/UI. Where we will need to update the documentation we'll create specific issues on the fly. 

NB: spelling mistake on the current README to correct before closing this issue.
<img width="554" alt="image" src="https://user-images.githubusercontent.com/109611779/188491599-5b2f0070-0183-4c5f-8837-29cfc1ea11bb.png">
