### ISSUE TITLE
Thyra : Import Same Private Key infinitely

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/thyra#303]
**Describe the bug**
Now you can import your wallet in thyra from your private key, this process needs to be doable only once with same private key, otherwise it creates a mess in the wallets layout.

**To Reproduce**

1. Go to 'thyra main page '
2. Click on 'load a wallet'
3. Paste your private key
4. Import your wallet
5. Do Same Process over and Over

**Expected behavior**
Load Wallet needs to be doable only once with same private key.

**Screenshots**
<img width="727" alt="image" src="https://user-images.githubusercontent.com/16125633/203830703-c920798c-6142-435f-8b05-2d67fcb5ba69.png">

**Thyra version**
v0.0.12 .

**Comment by SlnPons** [comment]
![Image](https://user-images.githubusercontent.com/109611779/204879204-8a78fa2a-05a2-4408-8ec1-2b7e4cc6802e.png)

Noice!! :)
