### ISSUE TITLE
*.massa certificate with SNI method

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#307]
**Context** 
It is not possible to certify the *.massa with classic certificate as it is not allowed for a company to own .com for instance. Here *.massa are considered being at the same level *.com. 
We would like to avoir using *.my.massa or other TLD like this. 

**Needs** 
* Certify all *.massa websites 
* Test the SNI method to dynamically generate a certificate for the requested *.massa subdomain using an embeded Authorisation Certificate (AC)

**How to** 

- [ ] Each time a user make an http request on xxx.massa, thyra will generate a certificate for xxx.massa and use it for the TLS Handshake
- [ ] To be accepted by the browsers, the certificate must be generated by mkcert tool. the mkcert binary should be downloaded a thyra installation and made available by thyra

## Technical details

- A specific [TLS configuration](https://pkg.go.dev/crypto/tls#Config) should be used to return a specific certificate based on the SNI information using the GetCertificate method.
- We can reuse the same key pair to all on-the-fly generated certificates. We just need to generate a new [certificate](https://pkg.go.dev/crypto/x509#Certificate) with the right domain name and then sign it with the CA's certificate generated by mkcert. 

As we are testing the method, simplification can be taken.

For instance, we can consider that the CA certificate is in the same directory as thyra-server or that the keypair for temporary certificate already exists at compilation time.

**Comment by gregLibert** [comment]
Potential useful tutorial about SNI  https://medium.com/@satrobit/how-to-build-https-servers-with-certificate-lazy-loading-in-go-bff5e9ef2f1f

**Comment by gregLibert** [comment]
Potential useful tutorial about certificate generation in Go https://medium.com/@shaneutt/create-sign-x509-certificates-in-golang-8ac4ae49f903

**Comment by peterjah** [comment]
@gregLibert  the 2nd link is not free to read.. "member only"...  altouth it seems very interseting 😄

**Comment by SlnPons** [comment]
@0xMazout in case it gives you more context, the convo and decision about SNI is here: https://github.com/massalabs/thyra/issues/154

**Comment by 0xMazout** [comment]
Research source
https://www.cloudflare.com/fr-fr/learning/ssl/what-is-sni/
https://www.cloudflare.com/fr-fr/learning/ssl/what-is-encrypted-sni/
https://blog.cloudflare.com/encrypted-sni/
https://blog.cloudflare.com/encrypted-client-hello/


![Image](https://user-images.githubusercontent.com/10938862/206410261-37e6b0c4-a7de-40bb-8278-d3285b05504f.png)

https://www.globalsign.com/en/blog/what-is-server-name-indication

**Comment by 0xMazout** [comment]
ESNI should clearly do the work and secure our navigation 
But what we have to clarify is :

- [ ]  First if go generate certificate is doable.
- [ ]  Second, if the certificate generate by go process is a CA authorized by the browser.
- [ ] If all top requirement are done,  we need to work on how to put our certificates on different browsers and OS.

Paralel Job
- [ ] Grow my knowledge on ESNI and how it's done 

@peterjah @gregLibert WDYT ?

**Comment by gregLibert** [comment]
> * [ ]   First if go generate certificate is doable.

Yes it is. Btw mkcert is developed in go 

> * [ ]   Second, if the certificate generate by go process is a CA authorized by the browser.

It doesn't work like that, the generated certificate need to be signed by a CA recogniezd by the browser. Right now we are using mkcert to generate the CA certificate. You just need to sign your newly created certificate with the CA certificate (i.e. the one generated by mkcert).

> * [ ]  If all top requirement are done,  we need to work on how to put our certificates on different browsers and OS.

You don't need to do that based on what is explained previously.

**Comment by 0xMazout** [comment]
Yesterday we talked with pierre about this and find a way in thyra to generate certificate on the fly in go with mkcert.

The problem was mkcert can't generate CA certificate for *.domain but he can for toto.domain 
So we derive the SNI concept to generate certificate on demand

Process : 
User ask a Website 
Mkcert generate certificate with specific domain asked by users
Mkcert install the certificate in the default browser of the user 
Then it should work 

This is the process i will try to make

**Comment by SlnPons** [comment]
Hey @0xMazout can you confirm that this is the right procedure to test this ticket please? 
1. Install the latest version of the main 
2. Run Thyra, and go to my.massa/thyra/*
3. Open a website *.massa 
4. The website should open using https? 

cheers

**Comment by 0xMazout** [comment]
To be honest i'm not sure it will work like this. 
What we actually ensure is we generate certificate for website on demand 
But i don't know if when you click on registery it will ask for https, this has to be tested 
But if you ask for https://*.massa using the right port it will provide a good certificate and it will work with this website

**Comment by 0xMazout** [comment]
We have to verify if we don't have to change the link in registry page and we don't have to change the process in DNS to catch Https instead of http

**Comment by 0xMazout** [comment]
To test : 

- Install the latest version of the main
- Run Thyra, and go to my.massa/thyra/*
- Open a website https://*.massa
- The website should open normaly and don't display a warning page
- then click on the locker in the top left screen and read the cerificate . The certificate should have the name of the website

**Comment by SlnPons** [comment]
Hey @0xMazout I probably did something wrong, but here is what I experience on my side

**Comment by SlnPons** [comment]
After testing with Greg, I created this issue to solve the experienced bug described above: https://github.com/massalabs/thyra/issues/381
