### ISSUE TITLE
Update the way we deserialize data in Thyra

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/thyra#319]
Context
In order to integrate with testnet 17 latest changes on the DNS SC, the way we fetch data from the the contract datastore has to evolve to take into account the fact that the list of domains owned by an account is not serialised in JSON anymore, but is stored as a byteArray in the storage.

How to
Before testnet 17 the list of domains was stored as a stringified JSON array of strings in the storage and Thyra awaited this type of data in order to print the various DNS names owned by a user.

    Update the type of data that is awaited by Thyra
    Update the deserialisation process to match the new data type
    Successfully print DNS names associated with an address on the personnal website page and on the registry page

The uploading of website seems to work be we cannot fetch it from Thyra
Fetching is from website and registry

Technical details
The args Class used in our SC store the size of the data in the header of the array for instance, if you want to store massa
massa = 109 97 115 115 97
but with Args massa = 56 0 0 0 109 97 115 115 97 (you add 4 bytes representing the size of massa)
Thyra deals with Strings and U64 in stored values (all is string, except chunk number and timestamps), you first need to know the data type and then add the good header to your key static Array
On the timestamp key from website storer you may have two header as we use new args().add(u64).add(u64)

**Comment by SlnPons** [comment]
As discussed, here is the branch on which you can continue if you want: https://github.com/massalabs/thyra/issues/310

**Comment by SlnPons** [comment]
@B-Naoufal how can i test this ticket please?
