### ISSUE TITLE
Bug internal/apihandler

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#32]
<img width="1067" alt="Screen Shot 2022-07-19 at 5 17 49 pm" src="https://user-images.githubusercontent.com/109611779/179786859-f8360f4b-3208-40e9-8cf6-bdd4017df272.png">

**Comment by gregLibert** [comment]
I tried to solve this bug by renaming the internal package to something else (int). But now there is another error:
```shell
$ go install github.com/massalabs/thyra/cmd/thyra-server@32-bug-internalapihandler
go: downloading github.com/massalabs/thyra v0.0.0-20220719154045-d0fe26d53d7d
go: github.com/massalabs/thyra/cmd/thyra-server@32-bug-internalapihandler: create zip: module source tree too large (max size is 524288000 bytes)
```
This issue is linked to https://github.com/golang/go/issues/29210, we need to : 
- reduce the size of the repo (by removing flutter ?)
- change installation by creating binaries artefact

@SlnPons @jwmdev @Trottoir @qdrn wdyt?

**Comment by qdrn** [comment]
I think we can move flutter to another repo since it will probably be the case in the long run anyway. (Also I probably pushed things that did not belong to a git repo which increased the size significantly).

**Comment by Trottoir** [comment]
Totally. agree, I think that : 
- build folders have to be removed from the repo ( in .gitignore )
- `app` folder is 700Mo so I think that we can separate that repo from the Thyra one ( maybe the `bridge` one also ? )

**Comment by gregLibert** [comment]
> - build folders have to be removed from the repo ( in .gitignore )

I'm not so sure about this one, those libraries are needed by the dart bridge.
If we don't explicitly expose those libraries using dart bridge will additionally imply to  compile the native libraries which can be painful.

One alternative is to put them as artifacts and generate them through a CI...

**Comment by qdrn** [comment]
> One alternative is to put them as artifacts and generate them through a CI...

We should probably do it in the long run. Making an issue.
