### ISSUE TITLE
Windows installation fails to download Thyra

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/thyra#320]
**Describe the bug**
When I execute the installer script from the command line as admin everything works fine but when I right click in the folder explorer and execute the script it downloads Thyra but fails to continue with the installation process.

**To Reproduce**
1. Go to your Thyra folder with the folder explorer
2. Go the scripts folder
3. Right click on the installer script and execute as admin

**Expected behavior**
The installer should keep installing Thyra after a successful download

**Screenshots**
![image](https://user-images.githubusercontent.com/45430752/205880680-cb214028-a927-4dae-ad24-53d1036229aa.png)

**Thyra version**
Main branch.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave
 - Version 1.46.133

**Comment by SlnPons** [comment]
Is this solved with the new install script in python @ASAPSegfault ?

**Comment by SlnPons** [comment]
@B-Naoufal is this solved with the new installer you're worked on?

**Comment by SlnPons** [comment]
Should be closed because working with the new installer.
