### ISSUE TITLE
Update Thyra to match the new DNS keys formatting

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/thyra#321]
**Context**
Currently we store the data of a user who wants to book a DNS in the following 2 keys :
- `recordKey` : defined as record + name, storing in value the websiteStorer address
- `ownerKey` : defined as owner + address of the user, storing in value the user address

We could store these in one key only. As of now we don't handle objects like these : 
`{"name": {"address": "XXX", "owner": "YYY"}}`.
But we can still make something more aligned with the way we use args.
The purpose of this issue is to update Thyra to match the new way the keys are formatted in the DNS.
Both the website and the registry page need to be updated.

**How to**
- Update how we fetch keys in the contract datastore to match the way we will store them after the issue below has been completed.
- Decode the data received
- Make sure DNS and website data are successfully shown on screen.

**Techincal details**
This issue needs to be done after this one : https://github.com/massalabs/massa-sc-contracts/issues/21
The encoding process is described in the linked issue.

**Comment by SlnPons** [comment]
To the Dev who's taking this issue, if https://github.com/massalabs/massa-sc-contracts/issues/21 is not merged on the main. Please contact @0xMazout to find out a solution to use his work :) 
Thanks!

**Comment by SlnPons** [comment]
@SebastienValla this issue needs to be merged before Testnet 18. I saw the PR still has some comments to be addressed. That would be great to address them quickly 😇
