### ISSUE TITLE
Thyra : Upload Website Not Working With an imported Wallet

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/thyra#326]
Recently We added the option to import wallets created outside thyra (using thyra-client), its working well, but those wallets are unable to upload websites.
![image](https://user-images.githubusercontent.com/16125633/206138424-7d019e41-5fb8-43af-8cd2-cdb9e7ba01e2.png)
I tried to verify how we store wallets in .env, and i found some differences between the  wallets imported and the ones created using Thyra 
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/16125633/206141554-cc7f2756-5763-44ef-a3cb-f78455d9e138.png">
There is a difference in the length of the PrivateKey

**Comment by SebastienValla** [comment]
duplicate with https://github.com/massalabs/thyra/issues/322
