### ISSUE TITLE
"certutil" is not available

### ISSUE THREAD

**Issue by gregLibert** [massalabs/thyra#333]
**Describe the bug**
mkcert complains that "certutil" is not available.

```shell
Warning: "certutil" is not available, so the CA can't be automatically installed in Firefox and/or Chrome/Chromium! ⚠️
Install "certutil" with "apt install libnss3-tools" and re-run "mkcert -install" 👈

Note: the local CA is not installed in the Firefox and/or Chrome/Chromium trust store.
Run "mkcert -install" for certificates to be trusted automatically ⚠️
```

**To Reproduce**

I simply use the installation script.

**Comment by SlnPons** [comment]
@gregLibert what is "certufil" please?

**Comment by gregLibert** [comment]
> @gregLibert what is "certufil" please?

certutil is the name of a package needed by MKCert for some configuration. This idea is to install this package at the same moment we are installing mkcert.

**Comment by SlnPons** [comment]
`Warning: "certutil" is not available, so the CA can't be automatically installed in Firefox! ⚠️
Install "certutil" with "brew install nss" and re-run "mkcert -install" 👈``

On MacOS
