### ISSUE TITLE
Mkcert certificates are not used by default

### ISSUE THREAD

**Issue by gregLibert** [massalabs/thyra#335]
When I run thyra, I have a https warning and the browser consider my.massa as dangerous:
```shell
sudo thyra-server 
2022/12/09 09:09:03 Connected to node server https://test.massa.net/api/v2 (version TEST.17.2)
2022/12/09 09:09:03 Plugin Manager initialization
2022/12/09 09:09:03 unable to find pluginDir: /root/.config/thyra/plugins
2022/12/09 09:09:03 Serving thyra server at http://[::]:80
warning: insecure HTTPS configuration.
	To fix this, use your own .crt and .key files using `--tls-certificate` and `--tls-key` flags
```

When I explicitely set thyra to use the certificate and the key generated by mkcert with the following command, it works as expected:

```shell
sudo thyra-server --tls-certificate /home/gregory/.config/thyra/certs/cert.pem --tls-key /home/gregory/.config/thyra/certs/cert-key.pem
```

**Comment by gregLibert** [comment]
Also exists on macos

**Comment by peterjah** [comment]
and thyra search for certs in $HOME/.config/thyra/certs

**Comment by gregLibert** [comment]
I just realize that on my side too. So my suggestion is to  add CAP_NET_BIND_SERVICE capabilities to thyra binary by doing sudo setcap CAP_NET_BIND_SERVICE=+eip thyra-server after installation.

This will solve two issue:
- the security pb of having a process running as root
- the certificate retrival

@peterjah wdyt ?

**Comment by peterjah** [comment]
> sudo setcap CAP_NET_BIND_SERVICE=+eip thyra-server

Yes !!
