### ISSUE TITLE
Tictactoe is not working on thyra

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#340]
**Context** 
Tictactoe is part of the Massa games. And so will be uploaded on each and every version of thyra web on-chain. It must work. 

**Needs** 
* As a user, when I open the tictactoe games I need to see that it's working so that I can play. 

**Technical details**
TO BE ADDED

**Comment by qdrn** [comment]
Is there any reason it's not working ? It's a rather simple page. The only thing that I can think of is that it requires https.

**Comment by SlnPons** [comment]
This problem seems solved on my side. I can't reproduce it.
