### ISSUE TITLE
HTTPS not working on MacOS

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#343]
**Context** 
We implemented the HTTPS certificates for the my.massa/* pages with this ticket: https://github.com/massalabs/thyra/issues/154 
But it does't work when I launched Thyra with the latest version of the release. 

See below the error: 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/109611779/206694452-5fa4f611-f8d5-432e-878a-cc1445c02499.png">

**Needs**
* As a user, when I installed the latest version of Thyra on my computer, I want to open my.massa/* page directly with https:// and without any warning messages.

**Comment by SlnPons** [comment]
@gregLibert fyi - it's not working on Firefix: 
`INFO: Installing MKcert and generating HTTPS certificates:
Created a new local CA 💥
The local CA is now installed in the system trust store! ⚡️
Warning: "certutil" is not available, so the CA can't be automatically installed in Firefox! ⚠️
Install "certutil" with "brew install nss" and re-run "mkcert -install" 👈

Note: the local CA is not installed in the Firefox trust store.
Run "mkcert -install" for certificates to be trusted automatically ⚠️

Created a new certificate valid for the following names 📜
 - "my.massa"

The certificate is at "/Users/slnpons/.config/thyra/certs/cert.pem" and the key at "/Users/slnpons/.config/thyra/certs/cert-key.pem" ✅

It will expire on 14 March 2025 🗓

PING test.massa (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.050 ms

--- test.massa ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.050/0.050/0.050/0.000 ms
SUCCESS: Thyra is installed and the .massa TLD resolution is configured. You're free to go!!!`

**Comment by SlnPons** [comment]
Also the user experience is: 
- run the install script
- accept that "the CA certificates modify the basic security certificates of your computer" via a pop-up 
- if you accept it, you have to enter the password of your computer. Twice: once to say it's ok, once to install it
- the script finishes and it's installed


So in conclusion: 
- It is working now on most browser. 
- But I don't think it's acceptable from a user perspective to have to do this. I won't have accepted to modify my security certificates via this pop-up... 

Do you think we could find a better way to manage this in the future? 
cc @gregLibert , @peterjah

**Comment by gregLibert** [comment]
> brew install nss

@SlnPons we need to add the previous command to the installation script to make it work for firefox.

**Comment by gregLibert** [comment]
> So in conclusion:
> 
> * It is working now on most browser.
> * But I don't think it's acceptable from a user perspective to have to do this. I won't have accepted to modify my security certificates via this pop-up...
> 
> Do you think we could find a better way to manage this in the future? cc @gregLibert , @peterjah

What we can do is to solve the problem for all target browser. But the security warning is "normal": we are doing something dangerous, it makes sens that the OS warns you.

**Comment by SlnPons** [comment]
> > brew install nss
> 
> @SlnPons we need to add the previous command to the installation script to make it work for firefox.

Could you be more specific so I can create the appropriate issue please? 
Do we need to add steps in the installation script for mac only or do you experience this "normal" behaviour on Linux and Windows too?

**Comment by gregLibert** [comment]
> > > brew install nss
> > 
> > 
> > @SlnPons we need to add the previous command to the installation script to make it work for firefox.
> 
> Could you be more specific so I can create the appropriate issue please? Do we need to add steps in the installation script for mac only or do you experience this "normal" behaviour on Linux and Windows too?

If **firefox** is used, we need to install:
- brew install nss on MacOS
- sudo apt install libnss3-tools on Ubuntu

**Comment by SlnPons** [comment]
Ok thanks @gregLibert. In order to close this issue but still improve the user experience as HTTPS is a very important things for users, I have created the following issues on Thyra repo: 

MacOS: https://github.com/massalabs/thyra/issues/367
Ubuntu: https://github.com/massalabs/thyra/issues/368
