### ISSUE TITLE
Possibility to delete websites on the registry page

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#344]
**Context**
We need to be able to delete the websites displayed on the registry page. In other terms, to delete a DNS entry.
While we're in testnet, someone (1 or many people) should be able to go on the registry page to delete websites. Either because they're compromising with bad code, bad images or simply because they don't work (--> inno team doing tests).

This is becoming an urgent need as Thyra is public so more and more people are uploading websites (1). And also because from Testnet 18 the ledger will be persistant and so the shitty websites will persist too (2). 
We need, internally, to be able to control this. 

**User flow** 
* As an Innovation team member, I want to be able to delete a website existing on the registry page so this DNS entry is not accessible by other by can still exist on the blockchain.

**How to**
Need to be discussed

- [ ] We have added a blackList key to the dns, and we fetch the blacklisted websites from the dns

**Comment by peterjah** [comment]
@SlnPons i just looked at Thyra code and it seems that the registry page returns all the websites registered in the DNS contract.
What do you mean by deleting ? its just hidding an entry from the registry page?
and if so, does it have to be persistant ?( i.e does the hidding stay if i restart Thyra?)
if its the case we will have to create a local state of the registry for each user.
Or maybe you need a possibility to filters this list agains some criterias?
So i think you should precise what is your need here so we can find the best solution!

**Comment by SlnPons** [comment]
@peterjah I added some context and info about this issue. I know it's centralised and we don't want to do that for now... it's only for testnet purpose. We'll for sure remove this SC later.
But what do you think? Keen to get your insight about how we could achieve this? Not sure if a "super" SC is the solution here.

**Comment by peterjah** [comment]
> @peterjah I added some context and info about this issue. I know it's centralised and we don't want to do that for now... it's only for testnet purpose. We'll for sure remove this SC later. But what do you think? Keen to get your insight about how we could achieve this? Not sure if a "super" SC is the solution here.

May i reformulate your need:
You don't want broken or shitty websites to shown on Thyra registry page ?

I don't think your solution is appropriate. maybe someone is doing some tests, or the website is work in progress, we don't know. Just deleting it without notice may be excessive imho.

Maybe a good solution would be to:
-  have a whitelist of websites we want to display on Thyra by default
-  displaying also those created by the current wallet
-  add an option to add any other entry in the list

**Comment by SlnPons** [comment]
I share your opinion that it might be excessive @peterjah  :/
Today, the main use case I have is the tests we do while developing where a lot of websites are uploaded either with shitty names, or with errors (as we're testing things) and can't be repaired or DNS name can't be changed.

I need a possibility to delete them easily. Otherwise we'll have to redeployed a new DNS and - atm - each time it's long and painful.

**Comment by SebastienValla** [comment]
We have added a blackList key to the dns, and we fetch the blacklisted websites from the dns

**Comment by SlnPons** [comment]
@SebastienValla should we write somewhere how it works and how we can use it internally in the Inno Team? 
Would help to test it too :D
