### ISSUE TITLE
Install script for Windows in Python

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#345]
Installation scripts become too complex and windows one is not working as expected.

Let's try to:
- use a real language to install thyra
- merge things with icon tray initiative (python based)

The idea is to:
- migrate existing installation script for windows to bat to python
- create a binary file

**Comment by gregLibert** [comment]
pyinstaller could be used to generate an executable binary file

**Comment by SlnPons** [comment]
Can't test, I don't have windows. Will assume devs test are enough. 
@ASAPSegfault how do I get the .py (?) of the script to update the doc using it please? 
Or maybe my question is stupid, what do I need to do to update the installation step-by-step?

**Comment by ASAPSegfault** [comment]
You don't need the .py
For now, each time we do a new release a file called thyra-installer is generated by the CI and available for download on Github.
Like in the artifacts on this page : https://github.com/massalabs/thyra/actions/runs/3748519129
The CI wraps the .exe file in a zip file, which the users need to download.
