### ISSUE TITLE
Generate build files in CI

### ISSUE THREAD

**Issue by qdrn** [massalabs/thyra#36]
One alternative is to put them as artifacts and generate them through a CI...

_Originally posted by @gregLibert in https://github.com/massalabs/thyra/issues/32#issuecomment-1192331029_

**Comment by thomas-senechal** [comment]
> can we close this issue?

I didn't saw that issue. IMO, this issue can be closed since it has been done in #79 (and so https://github.com/massalabs/thyra/pull/86).
