### ISSUE TITLE
Create a "Inno-template" repo to be cloned for each new repo

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#370]
**Context**
We are creating more and more repositories and each time we need to re-create a bunch of standards that we decided to use as a team like:
* issue templates 
* Release procedures
* and probably more technical basic too (TBD)
The objective of this ticket is to create a repo that will be used a modele to create new ones so that we have the basics immediately ready. From there, each repo could be modified and adapted based on their specific needs and characteristic

**How to**

- [ ] Create a new repo with all basic standards in use: 
* issue templates
* [ ] ask for an Admin to make this repo a template: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository
* [ ] Write a procedure on Notion on how-to use this repo as a model (https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template)
* [ ] Share the procedure with the team so everyone is aware of it

**Proposals**
We would like to reproduce easily:
- CI/CD
- labels
- branch protection rule
- role

feel free to propose solution or dismiss these ideas :)

**Comment by Thykof** [comment]
about CI/CD, it depends on the project, I don't know if we can define a template for this.

**Comment by SlnPons** [comment]
@Thykof I added your suggestion in the procedure on the ticket. Do you think it's a good idea? Feel free to edit and remove things directly! :)

**Comment by Thykof** [comment]
With template repository, only folders and files are created in the new repository (see github documentation) so labels, branch protection settings, role is out of scope. I think we should keep this in our procedure but not in github

**Comment by Thykof** [comment]
yes sorry ^^, fork is also not a solution because we don't want the history nor link with the template and it will also reproduce files. Git clone will also reproduce only files.

To conclude, if there is only issue templates, does this issue a priority?

**Comment by SlnPons** [comment]
It never has been identified as a priority, it's simply in the to do column as it's a very straight forward issue and it allows the team to increase its productivity.

**Comment by SlnPons** [comment]
This ticket is not blocked imo. It should be tackle in 5min, let's not discuss about it more time that we need to do it ;) 
Back to To Do.

**Comment by SlnPons** [comment]
Hey @Thykof I finally added the content of this ticket in the procedure you started. See here: https://www.notion.so/massa-innoteam/Inno-team-collaboration-process-32c466e36cf045629a134c9c7c9ee4d1#02ad993e29f742799052cec22960cb65 

Feel free to modify it. 
But I will close this ticket and communicate about it to the team now :) 
Thanks for the help!
