### ISSUE TITLE
Existing wallets disapeared from wallet page

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#377]
**Describe the bug**
All the wallets existing on my folder .config/thyra still exist on my computer but aren't displayed on the wallet page. 

**To Reproduce**
1. Install the latest Thyra version on the main 
2. Run Thyra and go on the wallet page
3. See no wallet listed on the page
4. Go to your .config/thyra folder and see the list of existing wallets

**Expected behavior**
All existing wallets should be listed on the my.massa/thyra/wallet page

**Screenshots**
<img width="301" alt="image" src="https://user-images.githubusercontent.com/109611779/210244172-2f1e80ca-2dd2-495d-99eb-0174465ca70f.png">

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/109611779/210244873-617773a9-66be-4fdd-a95a-3d059cf8753e.png">

**Thyra version**
Latest on the main on the 02/02/2023 at 3pm

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefow

**Comment by SebastienValla** [comment]
I don't think it is a real bug, it was only because testnet is down and you cannot fetch your wallets

**Comment by 0xMazout** [comment]
Blocked until : Need to be tested when innonet 17 or testnet 18 are live

**Comment by SlnPons** [comment]
Issue due to testnet being down. Can close it now.
