### ISSUE TITLE
Move Thyra to Innonet 17

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#378]
**Context**
Currently Thyra is running on Testnet 17 which is OFF until Testnet 18 is released. 
Even though it will be released soon, it as a bad practice to work on Testnet rather than on Innonet. Once the Innonet iso to the latest testnet exist, we should always work on the Innonet. 
For this reason and because we're currently blocked to test new things, we'll move to InnetNet 17 ASAP

**How to**

- [ ] Deploy Thyra and other products on Innonet 17

**Technical details**
- Make Innonet as default (in `cmd/thyra-server/main.go`)

**QA testing**
This task should be tested. 
The address `https://inno.massa.net/test17 (version SAND.0.0)` should be the one displayed at `thyra-server` launch.

**Comment by thomas-senechal** [comment]
Innonet 17 is fully deployed and available using the `--node-server INNONET` option at Thyra launch. 
I will make Innonet as default for Thyra to make sure we are not using the Testnet by default.

**Comment by SlnPons** [comment]
After discussing with @gregLibert this is not a good practice to hardcode this behaviour in the code. 
Especially because all releases should happen at any point of time, should be done by the PM and must be on the Testnet. 

So to simplify the process we will: 
* Keep the testnet on thyra-main repo by default 
* Create equivalent InnoNet by default to help partners to develop AND to prevent InnoNet team from being blocked by the testnet being down. 

In the future, when we'll encounter the need, we could: 
* Add a .env file in the code to be able to switch easily from one environment to the other.
