### ISSUE TITLE
Create Thyra Home page

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#383]
**Context**
Now Thyra as move from being a web-on chain product to becoming a plug-in manager, the front-end needs to reflect these changes so users can understand and project themselves. 
Thyra home page will allow users to navigate through the main functionalities of Thyra easily, natively and with obvious Call To Action (CTA).
This is the objective of this ticket.

**User flow**
1. User installs and run Thyra 
2. User can access Thyra Home page with the following URL: my.massa/thyra/home
3. User can see 3 things:
* The logo and name of the plugins already installed 
* A "more details" CTA that opens the plug-in manager page (see [other ticket to be added](https://github.com/massalabs/thyra/issues/386))
* A "Explore plug-in store" Button that opens the plug-in store. Will be developed later (so please let's discuss if we show the button but inactive or if it's better to not create the button until the store exists) 
NB: the plug-in store will be developed only when we'll need one - ie: not in short-term.

See wireframe below:
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/109611779/210623668-c35bb20b-f0c0-4254-a0f0-450079ee3dfe.png">

link: https://miro.com/app/board/uXjVOhqpH6I=/

**How to**

- [x] Using REACT framework build the home page as designed.
- [x] As this will be the first of a long serie of front-end built with this framework, it is required to set down a common base and define some standards about how the inno team will use this framework. Be aware of this and take care of it :) 
- [x] Feel free to send the list of components you'll use to PM so that I can select for you icons and other components so you don't waste time with this
- [x] Use the following URL to reference the Home page: my.massa/thyra/home
- [x] Make sure the home page is accessible in _https_ by default
- [x] Identify / Recognise installed plugins on Thyra to display them as designed on the Home page
- [ ] For the installed plugins (for now) - to be changed later: 
_nb: plugins' url format is: my.massa/thyra/author-name/plugin-name_
* Wallet: add icons + redirect to http://my.massa/thyra/massa-labs/wallet
* Web-on chain: fake it until we make it - icon + redirect to the "Websites" page
* Playground: icon + redirect to http://my.massa/thyra/massa-labs/playground
* Node-manager: icon + redirect to http://my.massa/thyra/massa-labs/node-manager
NB: icons will be fixed for now but the idea is to add it on the plug-in manifest to the creator of the plug-in can change it (icon = logo). See [ticket to be added](https://github.com/massalabs/thyra/issues/384).

**Technical details**
To be define **_PRIOR_** to start! 

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by 0xMazout** [comment]
Note before merge : To not forget , Ask to keisha a proper cut on our logos to avoid blank in png and svg.
for the front part i need an image , which have no border to align it well.

**Comment by 0xMazout** [comment]
Summary of work on this : 
Monday was working on the update of the Frontend and logo and pictures . Then learn about go generate and try to play with it
Today updating the routes and test

**Comment by 0xMazout** [comment]
ATM we will merge this and wait for another tasks to handle :
Routing url plugin form Thyra : Routing Mecanism

**Comment by 0xMazout** [comment]
React router is not working well with our swagger routing .

I have to create a dynamic endpoint

**Comment by SlnPons** [comment]
Hey @0xMazout sorry for the delay but I just tested the Home page, a couple of comments: 

1. I don't access the page in https by default. 
2. I need to type the full address my.massa/thyra/home to access the home page. Do you want me to create a new ticket for the users to type: my.massa/thyra and be automatically redirect to the home page? 
3. The plug-in list is static. Which will prevent me from doing a release any time soon.... 💀
So my 1st question is why this list is currently static? 
--> as far as I can see the Home page is linked to nothing. So it's not a problem coming from the fact that we currently have 2 plug-in managers.... 


Depending on the answer to my previous questions; I would suggest the following solutions: 
A. Create a static list of plugins and link icons to existing pages in Thyra. - worse case scenario
B. Link the home page to the "plugins" directory and detect which plugins are installed using the new plug-in manager - better than nothing
C. Do both of the above as today we only have 1 plug-in connected to the new plug-in manager and 2 (wallet + node-manager) to the old one. - best case scenario.
@gregLibert do you have any better solution to suggest? 

Happy to create another issue to address this point. But as this is written in this issue, I don't understand why we consider it ready to QA :(

**Comment by gregLibert** [comment]
@SlnPons I'm not sure what is the blocking point:
- access installed plugins: in that case using the API to list plugin should solve the problem for new plugin-manager-handled plugin
- access installable plugins: in that case a 4th approach could be to define all expected data by the front in a JS file. Adding a new plugin would simply consist in adding an entry in this JSON file.

**Comment by gregLibert** [comment]
> @gregLibert I am not comfortable putting in Done an issue where not all the points listed have been tackled and no ticket to tackle them is created. It means that I have to do the bodyguard for every point here... not the way I would like to work. That is the first blocking point.

Obvious but I didn't understand it from my first reading of your message.

> Other ones (listed above very clearly):
> 
> 1. No https: why? I thought https was now a standard for Thyra

Understood in your initial message.

> 2. my.massa/thyra/home or my.massa/thyra/ --> my.massa/thyra/home. Devs came to me to ask for this changed, I approved it. It is not done. Do we plan to address it in another issue?

Same it was crystal clear in your previous message.

My question was about:
> The plug-in list is static. Which will prevent me from doing a release any time soon.... skull

Is the problem here the fact that the installed-plug-in list is static or that it's difficult to add a new installable plugin ? Maybe both.

**Comment by 0xMazout** [comment]
Ok. Let me be clear. 

- The task was put in done to focus on the plugin manager page. Yes at the moment of the merge The task was not fully functionnal. But it was clear that we need external things(API) to continue on this. And in another sense i needed this for the plugin manager page.
 
- I take the responsability of this i'm alone working on this part. That was an opinionated decision . But it was clear Homepage was not ready to use on merge .

-The page is accessible with Https with no problem. i tested it. 
It's not accessible by default because we need to update the Interceptor in Thyra. It's a side effect of our technical choices.
When we launch my.massa/thyra eache page load is load in http we just need to update this. to https

 - The my massa/thyra/  subject : i pop up this , and the goal was to do this after we have something working it's an endpoint in the backend side it can be done in 15 minutes.
