### ISSUE TITLE
Plugin standardisation & naming convention

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#384]
**Context**
For Thyra to be able to treat all the plugins the same way, we need to define a standard way to create, name, and use a plug-in. 
In this ticket, we'll standardise: the naming convention for all thyra plugins as well as the informations that these plugins should share with thyra in order to work properly.

**User flow**
N/A - it's back-end only.

*As a developer, I want to be able to know the list of information to add on my plug-in as well as the naming convention so I can be efficient.
* As a PM, I want all plugins to work the same standard way.

**How to**
- [ ] Improve the current plug-in manager standards (manifest.json?) to require plugins to share: 
* name of the plug-in as: thyra-XX-plugin - mandatory
* name of the author (internally the author is: massalabs) - mandatory
* URL of the logo / icon of the plugin - optional
* short description of what the plug-in does (max X characters) - mandatory
* URL to use the plug-in - mandatory
* URL to plug-in home page details about what it is (To Be Discussed) - optional
* Author signature - optional: for the plug-in (will be needed to certified plugin) - optional
* Plugin version - mandatory
* Plugin language - mandatory

- [ ] Update Thyra readme or create a .md specify all this. IE: all new plugin should follow these standards

**Technical details**
To be defined PRIOR to start 

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by gregLibert** [comment]
[Right now](https://github.com/massalabs/thyra/blob/ccc79ca19c820ab0e80043cb4da5520c21f1eb79/pkg/plugin/plugin.go#L23-L27) the plugin is having:
- a name
- a description
- a logo
- an authority (network interface + port the plugin is listening to)
- an API description

**Comment by 0xMazout** [comment]
From the front side i need this type of information related to each plugin :
- Is Launched ?
- Is Update Available ?

- Maybe a response system more sharp. With Text error or Code error if request is not successed


Improvement : With our systems, we request plugins infos of all plugins. 
If we update a process we will re-render all the page. Maybe it can be good to have an endpoint to access plugin info with an ID to avoid big re-render.

**Comment by SlnPons** [comment]
I think most of the info you listed, will be available as soon as this ticket passes the review: https://github.com/massalabs/thyra/issues/425 
cc @peterjah to confirm

**Comment by SlnPons** [comment]
@peterjah I wasn't sure how to test this ticket, so I looked at the code. And I couldn't see any rules around the max characters for the strings. 
Do we have implemented any rules regarding this limitation?
Also, I think I understood that you made some fields mandatory, is my lecture of the code correct? 😎

Just so I know, thx!
