### ISSUE TITLE
Create the plugin manager page

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#386]
**Context**
To allow end-users to manage and interact with plugins they've installed, we need to have a dedicated page where they will be able to see the plugin list. 
The objective of this ticket is to create this page in Thyra.

**User flow**

1. User installs and runs Thyra 
2. User opens Thyra home page
3. User clicks on "more details" link
4. User is redirected to my.massa/thyra/plugin-manager page

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/109611779/210732514-a0769eb6-33f5-473c-b055-bb7a39029691.png">

**How to**

- [ ] Create plugin-manager page as designed here: https://miro.com/app/board/uXjVOhqpH6I=/. Note that icons and colours are indicative, don't hesite to share with me the components you'll use so I can select them for you and save you some times.
- [ ] Use URL mentioned above for this page
- [ ] Link the page to the Home page as described above
- [ ] Detect installed plugins and list them all on this page as designed using plugin manifest info
- [ ] Detect plugins status (active / inactive) to reflect this status in the toggle
- [ ] Link "Delete" button of the plugins to the deletion action of the plugin to remove it from user's machine in one click
- [ ] Link "Access" button to the plugin page to start using it (maybe the name of this button can be improved)

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by 0xMazout** [comment]
Proof of test on Homepage 


![Image](https://user-images.githubusercontent.com/10938862/217275623-6132583d-5a2e-46ea-9743-4214ac3ebd6b.png)

**Comment by SlnPons** [comment]
Yop @0xMazout can't seem to access the plug-in manager page. 

Here is what I do: 
* go on the latest version of the main 
* run thyra
* go to the home page 
* click on the plugin manager link 
* see below the error I have: 


![Image](https://user-images.githubusercontent.com/109611779/218778126-90f0fa1f-2d78-4818-b4b3-5814f9288930.png)

**Comment by 0xMazout** [comment]
Yes no problem will test it on my side then comeback to you

**Comment by 0xMazout** [comment]
To avoid this to all people who want to test plugin-manager 

GO here 


![Image](https://user-images.githubusercontent.com/10938862/218797641-802f805f-1542-4f56-a10b-ab244e339919.png)


Right click open terminal here 


![Image](https://user-images.githubusercontent.com/10938862/218797703-25da5aaa-e326-4076-998c-dab75cc699f5.png)



Then npm run build

You can test

**Comment by SlnPons** [comment]
> Report :
> 
> The go generate don't build the npm run build of the plugin manager . This is why this problem happened
> 
> I think the CI just doesn't integrate the plugin manager repo .

@peterjah any idea why this is happening by any chance?

**Comment by SlnPons** [comment]
CI problem mentioned above has been solved. 
However, the page in its default state is empty (see attached). The design (header) should appear at least, with a message or sth. Here I don't know if it's a bug or a normal behaviour. 

@0xMazout is it the normal behaviour when no plugin is installed? 
Will create appropriate tickets to handle this asap.


![Image](https://user-images.githubusercontent.com/109611779/220847224-d32f8f78-d0a9-45b3-84c9-eaf7dc824f69.png)

**Comment by 0xMazout** [comment]
> 

I don't think it's a normal behaviour. Do you want me to stop MassaTube and handle this now ?

**Comment by SlnPons** [comment]
Ok, good to know. 
No this page is in QA for such a long time it can wait...it will be the next priority :)

**Comment by 0xMazout** [comment]
If you can send a screen of the browser console log it would be helpfull

**Comment by 0xMazout** [comment]
Thanks
