### ISSUE TITLE
Allows Thyra to export its url client and debug options as an endpoint

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/thyra#388]
**Context**
Plugins need to communicate with the blockchain to get certain details such as the balance. To do that we need from Thyra an endpoint exporting its client.

**User flow**

* As a Dev I need a client endpoint that allows me to retrieve information from the blockchain to Thyra so that I can use it and/or share it with others (plugins, users etc...)

**How to**

- [ ] Create a new endpoint get in thyra to export its clients
- [ ] Add details to this endpoint to have a clear and usable endpoint for others (internal or external to the inno team)

**Technical details**
We create an endpoint returning the following : 
url : string, debug enable : bool, showresponsebody : bool

**QA testing**
* Check the swagger and see new endpoint created with all the details completed and understandable.

**Comment by SlnPons** [comment]
Duplicate from https://github.com/massalabs/thyra/issues/411
