### ISSUE TITLE
Update the Innonet creation and all related doc 

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#390]
**Context**
The innovation team botched the innonet creation and many steps have been forgetten and/or never added to existing procedures. As a result, we have living documents that are dead 😭 ⚰️ 
Let's give them life back.

NB: this should be done each time you modify or improve a process, on the fly and as a best practice for the team. This type of ticket should exist! It's a one time shot as no one reacted since Monday where the problem has been raised.

**How to**

- [x] Update the procedure of creation of InnoNet to make sure that all the important steps are written. Ex: create a DNS address, add this innonet + dns address to the code so the flag can be used (see https://github.com/massalabs/thyra/issues/287)

- [x] It seems that Innonet 17 and 16 have been deployed but no documentation nor monitoring have been done. These 2 points are critical as we have external users. To do AND to add to the procedure in Notion.
https://www.notion.so/massa-innoteam/DevOps-45b18089672744ca8b03cafbffa14093#abd67a2bcc4c4bc1803a5841198a6ca5 

- [x] Do the above for Innonet 17 so everyone can use them.

- [x] Update the external doc so partners can use InnoNets: https://www.notion.so/massa-innoteam/How-to-Use-Massa-InnoNet-f8798bf8499e4f988d0610742d7b91de

- [x] Add any other points that seems relevant to you! :) (These procedures exists for you not for me!)

**Comment by SebastienValla** [comment]
No Pr as it is doc, to review check https://www.notion.so/massa-innoteam/DevOps-45b18089672744ca8b03cafbffa14093#abd67a2bcc4c4bc1803a5841198a6ca5 and put ok in comment

**Comment by ASAPSegfault** [comment]
I corrected some english mistakes and requested two changes, otherwise I think everything is in there.

**Comment by SebastienValla** [comment]
done !

**Comment by gregLibert** [comment]
Are you sure we need to use the port ? see the documentation here : https://www.notion.so/massa-innoteam/How-to-Use-Massa-InnoNet-f8798bf8499e4f988d0610742d7b91de and the information here: https://inno.massa.net/ and the apache configuration here https://www.notion.so/massa-innoteam/DevOps-45b18089672744ca8b03cafbffa14093#abd67a2bcc4c4bc1803a5841198a6ca5

**Comment by SebastienValla** [comment]
I don't get you, where don't we need the port ?  I wrote the port related things on the 3 documents

**Comment by gregLibert** [comment]
Source :https://www.notion.so/massa-innoteam/How-to-Use-Massa-InnoNet-f8798bf8499e4f988d0610742d7b91de
![image](https://user-images.githubusercontent.com/16623956/211621420-4c0199ba-3a58-4b50-ac12-953503286f45.png)

**Comment by gregLibert** [comment]
And yes, according to the apache configuration here : https://www.notion.so/massa-innoteam/DevOps-45b18089672744ca8b03cafbffa14093#abd67a2bcc4c4bc1803a5841198a6ca5
![image](https://user-images.githubusercontent.com/16623956/211621898-c768a641-e5a3-4411-ab91-242502afc18b.png)
we don't need any port as the redirection from the external world is without any specific port...

**Comment by gregLibert** [comment]
It's also not clear to me if we need to install and configure testnet 16 when I read this:
![image](https://user-images.githubusercontent.com/16623956/211622283-e0415b6e-6ce2-4768-8daf-020bff9cbf98.png)

@SlnPons maybe you can help us :-).

**Comment by SlnPons** [comment]
@gregLibert indeed, we didn't updated the ticket descriptio .... my bad. 
InnoNet 16 (and 15) will be deleted so we decided that it wasn't needed to do it for them.

**Comment by SebastienValla** [comment]
add content on https://www.notion.so/How-to-Use-Massa-InnoNet-f8798bf8499e4f988d0610742d7b91de

**Comment by gregLibert** [comment]
I have also updated the procedure here: https://www.notion.so/How-to-Use-Massa-InnoNet-f8798bf8499e4f988d0610742d7b91de
