### ISSUE TITLE
Create Innonet 18 and delete older version listed in here

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#409]
**Context**
Testnet 18 is now stable. So it's time for us to create its equivalent in Innonet to secure our development is needed and to help our partners to develop too. 

**How to**

- [ ] Follow every step of this procedure: https://www.notion.so/massa-innoteam/DevOps-45b18089672744ca8b03cafbffa14093#abd67a2bcc4c4bc1803a5841198a6ca5
- [ ] Delete InnoNet 15
- [ ] Delete InnoNet 16
- [ ] Delete InnoNet 14
- [ ] Delete InnoNet 12

**Technical details**
* Follow all steps of the procedure.

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by ASAPSegfault** [comment]
Innonet 18 deployed here : https://inno.massa.net/test18
