### ISSUE TITLE
Durable and Resilient Thyra Install Script

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/thyra#435]
**Context**
We are improving the installation process for Thyra (thyra-server + thyra-app) by creating a Python script. During the process of merging pull requests for various operating systems, we found that our current coding methods did not adhere to our standards. The goal of this task is to maintain the existing logic while refactoring and cleaning our code. Our objective is to have one script per operating system, so that if a bug occurs for Windows users, it can be addressed directly without affecting non-Windows users.

https://github.com/massalabs/thyra/blob/main/scripts/thyra-installer.py

**How to**
*To accomplish this, we will be breaking down the thyra-installer.py script into three separate files:*

1. A global file where we will define the main class and gather all functions that will be used across all operating systems. This file will also include global variables used in the installation process and methods that can be overridden by other classes. Additionally, we will include try-except blocks and clear logging of errors, which will be recorded in a file called installation.log.
2. A Windows-specific script that defines a new class which inherits from the main class defined in the first file.
3. A MacOS-specific script, which includes its own class and is tailored to MacOS requirements.

**Technical details**
*New Code Structure template  *

`        

        
        logging.basicConfig(filename='installation.log', level=logging.DEBUG)
        
        class MultiOs:
            def __init__(self):
                """
                Set Globals Multi-os
                """
                pass
        
            def downloadFile(self.url, filename):
        
            def executeOSCommandOrFile(command, decodeBinary, shell=False):
        
            def configure_dns(self):
        """
        This method configures the DNS settings for the system.

        It will be implemented differently depending of the OS : Acrylic, DNSMasq
        """

        pass
        
            def install_thyra_app(self):
                """
                This method installs the IconTray Thyra app.
                """
                pass
            def main(self):
                print("Starting Installation of Thyra ...")
                .
                .
                .
                logging.info("Thyra has been successfully installed! Executable is located at : " + USER_HOME_FOLDER)
                logging.info("You can start using thyra from the menu bar located on the bottom of your screen")
        
        class WindowsOs(MultiOs):
            def __init__(self):
                super().__init__()
                """
                Set Globals Related To Windows
                """
        
            def configure_dns(self):
                """
                This method configures the DNS settings for Windows systems.
                """
                try:
                    # Windows specific steps
                except Exception as e:
                    logging.exception(e)
                    raise Exception("An error occurred while configuring the DNS settings for Windows systems.")
        
            def generateCertificate(self)
                 """
                This method generate certificate for Windows systems.
                """
                try:
                    # Windows specific steps
                except Exception as e:
                    logging.exception(e)
                    raise Exception("An error occurred while generating certificates for Windows systems.")
        
            def main(self):
                # Add any instructions you want to execute here
        
        
        if __name__ == "__main__":
            ThyraInstall = WindowsOs()
            ThyraInstall.main()
        
        class MacOs(MultiOs):
            def __init__(self):
                super().__init__()
                """
                Set Globals Related To MacOs
                """
        
            def configure_dns(self):
                """
                This method configures the DNS settings for MacOs systems.
                """
                try:
                    # Windows specific steps
                except Exception as e:
                    logging.exception(e)
                    raise Exception("An error occurred while configuring the DNS settings for MacOs systems.")
        
        
            def main(self):
                # Add any instructions you want to execute here
        
        
        
        if __name__ == "__main__":
            ThyraInstall = MacOs()
            ThyraInstall.main()
`
**QA testing**
*The 1-click install should work E2E  without any bugs, and a file called installation.log will be generated with logs*

**Comment by B-Naoufal** [comment]
@SlnPons  the ball is in your court

**Comment by SlnPons** [comment]
@B-Naoufal I can't see the linux script in your ticket? Are you sure there is absolutely nothing specific to Linux?

**Comment by SlnPons** [comment]
Check out this issue too please: https://github.com/massalabs/thyra/issues/201

**Comment by B-Naoufal** [comment]
@SlnPons first step : clean and refactor the 1 click install for windows and macos before adding new code, once we resolve this issue , the linux part can be added easily since it will just inherit from we've done in mac os part , so i prefer to keep this issue just for cleaning and refactoring what we already did for windows and macos

**Comment by ASAPSegfault** [comment]
> Check out this issue too please: #201. Will it be solved too?

It won't be solved.

**Comment by gregLibert** [comment]
@SlnPons Don't you think we should add CI tests to make sure the installation works properly?
I'm thinking of a CI that will run once a day to check for each OS that :
- the installation script works
- thyra can be launched
- an on-chain website can be access

Wdyt?

**Comment by SlnPons** [comment]
@gregLibert I am not sure to fully understand the difference between CI test and E2E test in this context. The reason I'm saying that is that I wanted to add 2 tickets in the board to create E2E test for Thyra: 
* One about Thyra installation on each OS (using Github actions) 
* One about Thyra functionalities such as website upload (focus on the back end first)

Is your proposal covering the first bullet point above?

**Comment by gregLibert** [comment]
Almost. Except that it won't be on all os, but only on those covered by this issue :-)

**Comment by SlnPons** [comment]
Ok thank you @gregLibert ! In that case @thomas-senechal let's discuss together to add CI tests on the OS covered by this issue. 
And add the same CI test on the other linux issue that you have created so that we cover correctly the 3 OS we're working on and our life will be way simpler when it comes to testing and maintaining :)

**Comment by SlnPons** [comment]
To move forward on this idea of CI tests, my objective would be to cover the following: 
* On Windows and MacOS (knowing that Linux will be covered on this issue https://github.com/massalabs/thyra/issues/449) test:
1. That the binaries exist on the latest release
2. That the binaries are executable after being downloaded (ie: no chmod or what ever to do)
3. The scripts on the latest release of Thyra are using the latest release of the thyra-app repo
4. That the scripts execute successfully for each OS 
4.1 Thyra is installed in the correct folder 
4.2 Thyra can be ran correctly (no error)
4.3 my.massa/thyra/wallet/ page can be accessed 
4.4 Thyra can be stopped correctly (no error)

The web on-chain will be tested on a specific issue see: https://github.com/massalabs/thyra/issues/465

Do you think the above CI can be added to this ticket or we should create a new one @gregLibert @thomas-senechal?

**Comment by thomas-senechal** [comment]
> To move forward on this idea of CI tests, my objective would be to cover the following:...

> 1. That the binaries exist on the latest release
I don't understand what you mean by this point. Is it like, checking that we have an installer in the latest release ? If so, when should we test this ? At each push ? At each new release ? And if we do at each release, should we do this test after the release is done ? 

> 2. That the binaries are executable after being downloaded (ie: no chmod or what ever to do)
AFAIK, the only way to fix it is to either:
- put the installers into a `.tar.gz` archive which will keep the file permissions -> easy to do
- use of a `.dmg` on MacOS for the installation -> probably not the best way of doing it since it's basically an archive, and I'm not sure we will be able to use it on Linux 🤔 
- use of a `.pkg` installer -> might take a lot of time to implement

IMO, using the `.tar.gz` format is the fastest and best way of fixing this issue until we have time to make an even better installer using `.pkg` format. 

> 3. The scripts on the latest release of Thyra are using the latest release of the thyra-app repo
Same questions as for first point.

> 4.4 Thyra can be stopped correctly (no error)
What is the "correct" way to stop Thyra ? For now, we just kill it using `CTRL+C` (or by sending signals, for example in [Thyra APP](https://github.com/massalabs/Thyra-Menu-Bar-App/blob/main/utils/background_process.py#L61)). Should we add an endpoint to stop Thyra ? Is it secure enough ? 

> Do you think the above CI can be added to this ticket or we should create a new one @gregLibert @thomas-senechal?
Depending on the answers to my previous questions, it could be really fast to implement or not. So I think we should create a new issue to discuss about it and implement it.

**Comment by SlnPons** [comment]
@thomas-senechal could you help me to your script on MacOS please? 
Here is what I did: 
* I went there https://github.com/massalabs/thyra/actions/runs/4173848124 
* I downloaded the arm64 binary 
* I made it runnable (chmod ...) 
* I run it
* I saw in my terminal: "successful installation" message 

nothing else happens; aren't we suppose to have the latest version of Thyra App being installed at the same time as this script?

**Comment by thomas-senechal** [comment]
> @thomas-senechal could you help me to your script on MacOS please? Here is what I did:
> 
> * I went there https://github.com/massalabs/thyra/actions/runs/4173848124
> * I downloaded the arm64 binary
> * I made it runnable (chmod ...)
> * I run it
> * I saw in my terminal: "successful installation" message
> 
> nothing else happens; aren't we suppose to have the latest version of Thyra App being installed at the same time as this script?

Hi @SlnPons !

Thyra App is installed in your $HOME along Thyra. But, we do not start it as the previous version did. 
You can start Thyra App using `$HOME/thyra-app` on MacOS.

**Comment by SlnPons** [comment]
@gregLibert may I have your opinion about the best way to solve this problem: 

As a user, I want to download the binary from Thyra release (or other entry point, up to us) to install thyra and its app AND be able to double click on it once downloaded for the installation process to start. 

--> today the binary is not executable and so it prevents non-dev users from using it simply... which is a non-sense. 
Any ideas? 
See below Thomas' suggestions: 

```AFAIK, the only way to fix it is to either:

put the installers into a .tar.gz archive which will keep the file permissions -> easy to do
use of a .dmg on MacOS for the installation -> probably not the best way of doing it since it's basically an archive, and I'm not sure we will be able to use it on Linux 🤔
use of a .pkg installer -> might take a lot of time to implement
IMO, using the .tar.gz format is the fastest and best way of fixing this issue until we have time to make an even better installer using .pkg format.```
