### ISSUE TITLE
Create a DeploySC EndPoint

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/thyra#441]
**Context**
There is no endpoint to deploy SC from Thyra, we needed it for the hackathon, It is created but need to be debuged and cleaned

**How to**
Deploy a SC using a Thyra endpoint

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by 0xMazout** [comment]
Lets get in , i'm taking the 442 branch and try to debug it :)

**Comment by 0xMazout** [comment]
At this moment we have not a proper way to test this at 100%.

The Endpoint looks like working , but the front of MassaTube is not ready to test it properly. 

I have made some tests and i have 204 response

I failed to testit with swaggerEditor. 

My idea was to push this. And when we have a proper way to test it. Verify if the Endpoint send what it has to do . 

My knowledge on how to test this is very limited. If some one is better to do this feel free to verify this.

From my side . I think it's not urgent to test this at 100% now, we will test it when massa tube will be ready for this

**Comment by 0xMazout** [comment]
Ok So the Endpoint was working. 

But when we go through the process we were waiting for an Event. 
And if an Event wasn't provided we were stuck in an infinite loop.

Deploy SC is now dynamic on event and process is faster

I upgraded the process and added some barrier to provide some info in case of bugs

I add a way to validate an address testing the prefix and the length (located in wallet)

**Comment by SlnPons** [comment]
@SebastienValla sorry to bother but could you confirm that thyra on testnet 20 is using this new endpoint and so if the website deployment works, this endpoint works? 
Cheers

**Comment by SebastienValla** [comment]
Yes it is working well ! 👍

**Comment by ASAPSegfault** [comment]
@SlnPons the website deployment process is not using the new endpoint

**Comment by SlnPons** [comment]
@thomas-senechal when deploying the innonet and so new DNS for thyra on the innonet, did you use this new endpoint?

**Comment by thomas-senechal** [comment]
> @thomas-senechal when deploying the innonet and so new DNS for thyra on the innonet, did you use this new endpoint?

No, I didn't used this endpoint

**Comment by SlnPons** [comment]
Ok, thanks a lot everyone! :) 
Will create an issue to use this endpoint with Thyra then.
