### ISSUE TITLE
/mgmt/wallet/{nickname} not working

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/thyra#444]
**Describe the bug**
During hackathon we were not able to fetch only one wallet with this call, it may come from Thyra or from our Dapp

**To Reproduce**

**Expected behavior**

**Screenshots**

**Thyra version**
The version of Thyra the bug is present in.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows...]

**Additional context**

**Comment by 0xMazout** [comment]
![Image](https://user-images.githubusercontent.com/10938862/218694049-d55517c4-7683-406c-9cfd-ccd2220a788f.png)

Currently on debuging

**Comment by SlnPons** [comment]
@0xMazout please make sure to use the plug-in wallet and not Thyra wallet please for check and potentially solve this bug.

**Comment by 0xMazout** [comment]
Solved by https://github.com/massalabs/thyra/pull/458#pullrequestreview-1297720718
