### ISSUE TITLE
Feature Request: Thyra Web-On-Chain config file

### ISSUE THREAD

**Issue by mickael-btc** [massalabs/thyra#446]
**Context**
Possibility to personalize the thyra server for each website.

**User flow**
Developers would write a config file at the root of a zip file that contains the website. It would contains some settings and different strategies like `Access-Control-Allow-Origin`.

**How to**
load a `thyraconfig.json` file located in the zip, parse and load settings and finally apply them.

**Comment by SlnPons** [comment]
@mickael-btc could you help me to identify the value of such a feature from a user perspective please? 
By reading your issue, I understand that it will allow the website devs to have more flexibility with the resourcing they wqant to use to create their website. For instance, retrieve images stored on another server than the blockchain. 

Keen to understand a bit more the use cases this feature could cover to prioritise it correctly :) Thanks!
