### ISSUE TITLE
Use the Python installer for Linux installation

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/thyra#449]
**Context**
https://github.com/massalabs/thyra/issues/435 treats the cleaning and improvement of our Python Installer. Once this issue is fully done, we want to add a Linux installer based on the same architecture and using the same global functions.

**User flow**
- User download a installer for Linux
- User starts the installer on their computer
- Thyra and it's dependencies are automatically installed by the installer
- User can use Thyra

**How to**
- [x] Make sure https://github.com/massalabs/thyra/issues/435 is done
- [ ] Check how the MacOS and Windows are made following https://github.com/massalabs/thyra/issues/435
- [ ] Implement the Linux installer in a very similar way

**Technical details**
- The way you should implement the Linux installer is available in https://github.com/massalabs/thyra/issues/435. For more details, please check the code used for the MacOS and Windows installers following https://github.com/massalabs/thyra/issues/435 merge

**QA testing**
- Remove Thyra if you already have it installed on your computer
- Download the installer for Linux
- Run the installer
- Try to run Thyra

**Comment by SlnPons** [comment]
@thomas-senechal do you think you can finish this today / tomorrow so all scripts are up to date? 
Happy to push back the CI test if needed. As you have a deep understanding on the installer now, it should be easier for you than for any other devs to do this task quickly.

**Comment by SlnPons** [comment]
@gregLibert @thomas-senechal I believe that you have discussed about a long-term (LT) solution. Well it will be needed to implement it ASAP as the node-manager plugin is using the new plugin manager and so this bug will prevent MacOS users from using it. 

Could you discuss together about the solution to implement for it to work LT and let me know how long it could take to develop it please? 
Node-manager will be ready by the end of the week.
Thanks

**Comment by SlnPons** [comment]
@gregLibert do you think you can finish this ticket soon please? 
What's its status exactly? Because it's defo not "in progress"

**Comment by gregLibert** [comment]
> @gregLibert do you think you can finish this ticket soon please? What's its status exactly? Because it's defo not "in progress"

@SlnPons I've started working on it, but I've fixed some issues on ThyraApp part. There is more to do but I think i have done enough to unblock this subject.

**Comment by SlnPons** [comment]
And I think this PR is related so could be put to done if the test is ok: https://github.com/massalabs/thyra/pull/472
