### ISSUE TITLE
Node Manager can't be accesed with link from front, due to interceptors

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/thyra#462]

**Comment by 0xMazout** [comment]
Context : 

We want to reach NodeManager page from Thyra Homepage.

To do this we have to make an open.window(URL)

The problem is the following. 

Atm Node manager is not following the go swagger routing from thyra

Node Manager is self hosted on specific port : 4200 (i think)

So to access the url is my.massa:4200

And this specific url can't be reproduced from the front because of the interceptors


![Image](https://user-images.githubusercontent.com/10938862/218052503-1c40bc1c-c008-4894-84fa-ab77c4df005d.png)

gave me this 



![Image](https://user-images.githubusercontent.com/10938862/218054747-5ed81e61-1203-429b-9270-3d67b2cd6ca0.png)



then try this : 



![Image](https://user-images.githubusercontent.com/10938862/218055217-c1c5c2a9-dce3-4448-94e1-5d54bc4c3f75.png)



gave me this 




![Image](https://user-images.githubusercontent.com/10938862/218055252-cfc8325e-8cb2-4512-93a1-b792d30cef7b.png)

**Comment by SlnPons** [comment]
Hey @peterjah this problem should be solved if we move the node-manager plugin to the new thyra plugin manager, isn't it? 
If so then let's try to do so as part of our milestone. What do you think? 
cc @Thykof

**Comment by peterjah** [comment]
Yes totally. I'm closing the issue
