### ISSUE TITLE
Plugin Manager stop , put plugin in crashed status only on Windows

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/thyra#463]

**Comment by 0xMazout** [comment]
When we call Stop command , the plugin get put in crashed status only on windows, 

@peterjah  tested it on linux and it appeared it's not happening in Linux.

This is clearly related to the interepretation of the response of kill processes in windows

**Comment by 0xMazout** [comment]
![Image](https://user-images.githubusercontent.com/10938862/218066515-4f335b3b-2cd3-4c84-b57c-0551243a00f7.png)

**Comment by gregLibert** [comment]
> cc @gregLibert can you confirm the ticket you created will allow us to detect problems like the one reported by Lucas on this issue please?

I initially wasn't thinking about testing the API by OS, but yes it can be done :-)

**Comment by gregLibert** [comment]
@0xMazout can you share the log of the failure ? Are you sure the DNS was propely setted ?

**Comment by gregLibert** [comment]
@0xMazout can you tell me if the stop plugin returns an error ?

**Comment by gregLibert** [comment]
I think that the error is frome [here](https://github.com/massalabs/thyra/blob/dea7998c3d5da9ccdc83cfc91a1b2276a7f9c5db/pkg/plugin/plugin.go#L144-L150). I guess that the tested return value is only for linux.
Can someone on macos can test it ?

**Comment by SlnPons** [comment]
@gregLibert yep, will do. And let you know :)

**Comment by SlnPons** [comment]
@Pierregvx could you manually test this bug and try to reproduce it on Windows please?
Ping me if you need more details.

**Comment by SlnPons** [comment]
On macOS it seems that this problem is solved with the latest version of the plugin manager of thyra as I can't reproduce the problem. 
However, on windows this problem is persistent as tested by Pierre.

**Comment by gregLibert** [comment]
I think the error is here : https://github.com/massalabs/thyra/blob/main/pkg/plugin/plugin.go#L144

My guess is that:
- on linux and mac the error content is "signal: killed".
- on windows it's different ("exit status 1" from what I understand from the log shared by Lucas).

My hypothesis  should be easy to fix and test :-)

**Comment by SlnPons** [comment]
@0xMazout can you test if this issue when building the front-end page and put it in done if so please?
