### ISSUE TITLE
BUG - thyra installation from source code is not working

### ISSUE THREAD

**Issue by gregLibert** [massalabs/thyra#467]
On linux at least, compilation (`go build cmd/thyra-server/main.go`) after cloning the repo (`git clone ... `) is not working and returns the following error:
```shell
go build cmd/thyra-server/main.go
int/api/thyra.go:22:12: pattern dist: no matching files found
```

My configuration: `Ubuntu 22.04.1 LTS`

**Comment by gregLibert** [comment]
To solve this you need:
- to have node installed on your computer
- generate the react part by doing:
```shell
go generate gen-frontend.go
```

@SlnPons I think that we need to add that in the readme / builder documentation :-)

**Comment by SlnPons** [comment]
@gregLibert I'm confused between the solution you're highlighting and the title of the bug. 
Is it Thyra that is not working using the install script? or is it the node-manager plugin that is not reachable after installing thyra with the script? 

+ I am sorry to say that but if you would use the bug templates it will help me to understand what you did 😇
Feel free to remove parts that you think aren't needed to understand the problem, it will help to update the templates over time. But still a bit more context, would help others to relate :)

**Comment by gregLibert** [comment]
> Is it Thyra that is not working using the install script?

Nope. As mention it's when I compile the project after cloning the repo. I have updated the description to add the effective command that I'm used.

> is it the node-manager plugin that is not reachable after installing thyra with the script?

Nope nothing related to the node-manager here.

>  I'm confused between the solution you're highlighting and the title of the bug

For the CI, I need to install thyra by hand. And to do so I need to compile thyra itself from the source code. I will change the scratch of the description to from source code.

**Comment by SlnPons** [comment]
@gregLibert @Pierregvx is this issue solved with the new contribute file that you wrote?

**Comment by gregLibert** [comment]
> @gregLibert @Pierregvx is this issue solved with the new contribute file that you wrote?

Yes, it's [here](https://github.com/massalabs/thyra/blob/main/CONTRIBUTING.md?plain=1#L30), even if the INSTALLATION.md could be improve by mentioning the npm part...

**Comment by SlnPons** [comment]
Ok, I'm in the process of re-writing the installation.md. @Pierregvx would you mind if I add you as a reviewer so that you can add the npm part please?
