### ISSUE TITLE
Error when go generate with Windows

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/thyra#469]
**Describe the bug**
PS C:\Users\Sébastien\Documents\GitHub\thyra> go generate
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Sébastien\Documents\GitHub\thyra/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Sébastien\Documents\GitHub\thyra\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sébastien\AppData\Local\npm-cache\_logs\2023-02-13T17_09_32_471Z-debug-0.log
gen-frontend.go:4: running "npm": exit status 0xfffff026

**To Reproduce**
in windows run go generate from thyra folder

**Expected behavior**

**Screenshots**

**Thyra version**
The version of Thyra the bug is present in.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows...]

**Additional context**

**Comment by SlnPons** [comment]
@SebastienValla what are you trying to achieve with a go generate? 
Just so I can understand the problem and try to prioritise it correctly please ;)

**Comment by SebastienValla** [comment]
@SlnPons  when you dev on thyra you need to run go generate to generate files based on swagger and to build the front end

**Comment by peterjah** [comment]
@SebastienValla this should be fixed now. The doc is updated as well.
`go generate` will build the swagger
and the frontend must be build with `go generate ./web/...`

Can you confirm its working well and if yes close the issue?

**Comment by SebastienValla** [comment]
> 

It is working ! thanks
