### ISSUE TITLE
Add CI tests on Thyra installation process for all OS

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#473]
**Context**
Installing Thyra is the entry point for all users so this process must be monitored. 
Adding CI tests on this process will enable us to save time and to systematically detects errors. 

The objective of this ticket is to cover all OS with a CI test. 
_Break down this ticket (considered it meta) if needed._

**How to**

- [x] Test Thyra installation process end-to-end on the following OS: MacOS, Linux Ubuntu, Windows 11. 
- [ ] This test should cover: 
* for each release (should we do each push? what do you think?)
* that the binary / artifact exist
* that the script installs Thyra-app latest version
* that Thyra can be start / stop / restart without error

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by thomas-senechal** [comment]
> for each release (should we do each push? what do you think?)

I think we should do it for each push on `main` branch. As we do for the `thyra-server` and `thyra-installer` builds.

> that Thyra can be start / stop / restart without error

I think we should use Python to do that. We could start Thyra from a Python script, keep the PID to be able to stop Thyra, check the logs to check if we have errors and/or the expected outputs, and then, if it didn't crashed, we could stop Thyra.

I think, at some point, we should also have specific tests for the plugin manager. We could install the [`hello-world` plugin](https://github.com/massalabs/thyra-plugin-hello-world) and check if it's running as expected. Maybe we should make another issue to discuss about it.

**Comment by SlnPons** [comment]
@Pierregvx could you have a look at this issue and let me know what part of the scope you already have covered please? 
Please link issues that you used to do the work so we have tracability. Cheers 


cc @gregLibert in case my vocabulary isn't the right one, you may be able to translate all that to Pierre.

**Comment by Pierregvx** [comment]
hey, my script currently handle installation on all 3 os from the latest or a specific version. The start/stop feature is not here yet
the issues are [#4](https://github.com/massalabs/thyra-test-e2e/tree/4-feature-thyra-automatic-installation) , [#5](https://github.com/massalabs/thyra-test-e2e/issues/5) and (#12)[https://github.com/massalabs/thyra-test-e2e/issues/12)

**Comment by SlnPons** [comment]
Perfect, thank you @Pierregvx :) 
I think I'll remove the start / stop tests as I think we could get rid of them (and always run thyra in the background).
