### ISSUE TITLE
Improve Thyra installation scripts

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#474]
**Context**
Make it user friendly. 
Current scripts install Thyra and Thyra-app but no message exist on the terminal, and the app is not opening either; which means that from a user perspective you stay blocked at the end of the installation.

**User flow**

1. User download the binary on Thyra latest release to install Thyra and its app 
2. Binary is downloaded on User's computer 
3. Binary is executable immediately (no action from user) ie: Once the download is finished, user double click on it to start the installation process. 
4. Once the installation process is finished, user sees: a clear message on the terminal explaining that Thyra app has been installed AND will open automatically AND specify where the app has been installed so user can find it easily.

**How to**
See above.

**Technical details**

- [ ] Add the print for Thyra location in [`startInstall` in `installer.py`](https://github.com/massalabs/thyra/blob/4a921105515acb9e17b440f04df62a14b6aa51b7/scripts/installer.py#L183)
- [ ] Add a function `startThyraApp` that will start Thyra App in [`installer.py`](https://github.com/massalabs/thyra/blob/4a921105515acb9e17b440f04df62a14b6aa51b7/scripts/installer.py). If needed, override it for MacOS, Windows and/or Linux. Make sure it stills runs after the end of the installer. You can base this on [this](https://github.com/massalabs/thyra/blob/4a921105515acb9e17b440f04df62a14b6aa51b7/scripts/thyra-installer.py#L282)

**QA testing**

1. Download the installer, either from the latest release or the link specified in the PR description
2. Check that it is installing `thyra-server` and `thyra-app` in the directory displayed at the end of the script.
3. Check that Thyra App has been started as expected and that it is running properly (Start Thyra, Stop Thyra...)

**Comment by SlnPons** [comment]
@thomas-senechal sorryyyy 😇
I can't find the latest installer in the PR description. Could you help please? So I can test before doing a new release? :) 
Ty

**Comment by thomas-senechal** [comment]
> @thomas-senechal sorryyyy 😇 I can't find the latest installer in the PR description. Could you help please? So I can test before doing a new release? :) Ty

Hey ! 

You can find the binaries on the latest CI on `main` : https://github.com/massalabs/thyra/actions/runs/4305777983

**Comment by SlnPons** [comment]
Sorry for the delay, but it's still not working as described on the user flow of this issue.
After downloading the file is not executable.

**Comment by Thykof** [comment]
@SlnPons you can QA review this one  :)
