### ISSUE TITLE
Hello world dnsmasq problem on MacOS

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#476]
**Describe the bug**
Plugins can't communicate with Thyra using the new plugin manager as the DNS used is 192.168.1.254:53 instead of 127.0.0.1:XXX. 

**To Reproduce**

1. Git pull the latest branch version of thyra/main
2. Go to the hello world repo and download the binary for your MacOS (in my case: ARM64)
3. Create manually the "my_plugins" folder in the "Thyra" folder in .config/
4. Add the downloaded folder unzipped to the "my_plugins" folder created
5. Run Thyra on your terminal (go run cmd/thyra-server/main.go) 
6. Access this page: my.massa/thyra/plugin-manager/ --> empty to so no hello world plugin 
7. Use postman collection to get the status of the plugin: "crashed" 
8. See console logs
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/109611779/220955184-56988acd-de9c-4e3a-b98c-065060587c5f.png">

**Expected behavior**

When you download and install the plugin "hello world" you can see it on the plugin manager page (my.massa/thyra/plugin-manager)

**Thyra version**
v0.1.9

**Desktop**
 - OS: MacOS
 
**Additional context**

**QA Testing**

1. Download the installer.
1.a. If you downloaded the installer from GitHub Action artifacts, you need to unzip the file and, on Linux and MacOS, make it executable with `chmod +x thyra-installer`.
3. Disable DNSMasq.
10. Run the installer.
11. Check that some files are present and well configured:
5.a. Check that you have a `thyra-server` and a `thyra_app` executables in your `$HOME` directory.
5.b. Check that you have a `dnsmasq.d/massa.conf` file and that it's content is the following:
```
address=/my.massa/
no-resolv
server=8.8.8.8
server=8.8.4.4
```

You can do it by running:
```bash
cat $(brew --prefix)/etc/dnsmasq.d/massa.conf
```

4.c. Check that you have a `massa` file in your `/etc/resolver` directory and that it's content is the following:
```
nameserver 127.0.0.1
````

You can do it by running:
```bash
cat /etc/resolver/massa
```

4.d. Check that you have a `/etc/resolv.conf` file and that it contains the following:
```
nameserver 127.0.0.1
```

You can do it by running:
```bash
cat /etc/resolv.conf
```

12. Run `thyra_app` and check that the application is running.
13. Right click on the tray icon and start Thyra.
14. Check that the application is running.
15. Open a browser and go to <http://my.massa/thyra/websiteCreator/index.html>.
16. Stop Thyra using the tray icon.
17. Close Thyra App.

**Comment by thomas-senechal** [comment]
Here is what we found out with @gregLibert 

The resolver isn't set to `127.0.0.1` in `/etc/resolv.conf` by default and so, some tools that are only using `/etc/resolv.conf` cannot be redirected to `127.0.0.1`. This file being automatically generated, we can't just modify it.

On MacOS, the best way we found to fix this issue is by setting the resolver of each interface following [this guide](https://cleanbrowsing.org/help/docs/manually-change-dns-on-a-mac-terminal/). This also requires us to change the nameservers in dnsmasq to have a config file `.../etc/dnsmasq.d/massa.conf` as follow:
```
address=/.massa/127.0.0.1
no-resolv
server=8.8.8.8
server=8.8.4.4
```
Otherwise, users won't have access to internet anymore. This method clearly needs some more researches to make sure users are fine with the nameservers we will set for them or match their current configuration.

**Comment by gregLibert** [comment]
@SlnPons the previous suggestion should unlock your task of testing the hello world plugin. 
But we need to do something cleaner...

**Comment by SlnPons** [comment]
@gregLibert @thomas-senechal I believe that you have discussed about a long-term (LT) solution. Well it will be needed to implement it ASAP as the node-manager plugin is using the new plugin manager and so this bug will prevent MacOS users from using it.

Could you discuss together about the solution to implement for it to work LT and let me know how long it could take to develop it please?
Node-manager will be ready by the end of the week.

**Comment by SlnPons** [comment]
@thomas-senechal Hey could you help me to install the right DNS please? 
Here is what I did: 
1. change the DNS manually on my MacOS
<img width="776" alt="image" src="https://user-images.githubusercontent.com/109611779/220125768-b8173456-aa72-458f-a5d6-c4b68f532994.png">
2. Try to access the config file for dnsmasq but can't find it 😅
<img width="982" alt="image" src="https://user-images.githubusercontent.com/109611779/220125894-9119b7f5-eb48-4600-8586-621486b321c4.png">

**Comment by thomas-senechal** [comment]
> @gregLibert @thomas-senechal I believe that you have discussed about a long-term (LT) solution. Well it will be needed to implement it ASAP as the node-manager plugin is using the new plugin manager and so this bug will prevent MacOS users from using it.

I stopped my researches with [that comment](https://github.com/massalabs/thyra/issues/476#issuecomment-1431434774).

As we said with @gregLibert , we definitly need to find a clearner way of implementing this. 

> Could you discuss together about the solution to implement for it to work LT and let me know how long it could take to develop it please?

For sure. 

> Hey could you help me to install the right DNS please?
Yes !

Your DNSMasq config file is located in `$(brew --prefix)/etc/dnsmasq.d/massa.conf`. So you can modify it using:
```
sudo nano $(brew --prefix)/etc/dnsmasq.d/massa.conf
```

This command will asks for your password and then open the file using `nano`. If needed, we can make a call to fix this issue

**Comment by Thykof** [comment]
I can't reproduce the bug even though `dig my.massa` is telling me `SERVER: 192.168.1.254#53`. So we can not conclude on whether we should merge this PR #488  or not.
