### ISSUE TITLE
Sign from a website

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/thyra#479]
Hey, I see that the page `https://my.massa/thyra/websiteCreator/index.html` can trigger signatures from Thyra wallet.
Is there some sort of API I should put in my website so that it can do the same, for instance connect with a basic "Connect" button or "Swap" like on [Uniswap](https://app.uniswap.org/#/swap)?

**Comment by SlnPons** [comment]
@sebastien-forestier you should connect your app to thyra-wallet-plugin. You can find docs to install it here: https://github.com/massalabs/thyra-plugin-wallet/blob/main/README.md 

And the postman collection for available endpoints is here: https://github.com/massalabs/thyra-plugin-wallet/tree/main/api 


If you need any endpoints that don't exist yet, please share you need with us as we make it better and better on the fly each time we have a new need. 
I hope it answers your question.

**Comment by sebastien-forestier** [comment]
Thanks for your answer!
Is it included inside Thyra when I launch `thyra-server` ?
Also, do we have a js example using the API (e.g. that signs a callSC) ?

**Comment by gregLibert** [comment]
@sebastien-forestier I think that using a wallet's private key to sign in an application is a (very) bad practice for the following reasons:
- when you sign something today you don't know what you are signing. Is it the access to Gummu? A transfer of all my coins to a stranger?
- you expose your identity. If I sign on site A and site B and site C my wallet is no longer anonymous.
- At some point the regulation will get involved, I think in particular to the GDPR in Europe, the wallet identifier will be rightly considered as a personal data and all applications using it will be in trouble

That being said, and to answer your question, there is no JS lib to wrap the calls to Thyra, but we have a swagger file [here](https://raw.githubusercontent.com/massalabs/thyra-plugin-wallet/main/api/wallet_api-v0.yml) that you can use in [swagger-editor](https://editor.swagger.io/). The endpoint you are looking for is `/rest/wallet/{nickname}/signOperation`.

**Comment by sebastien-forestier** [comment]
> @sebastien-forestier I think that using a wallet's private key to sign in an application is a (very) bad practice for the following reasons:
> 
>     * when you sign something today you don't know what you are signing. Is it the access to Gummu? A transfer of all my coins to a stranger?
> 
>     * you expose your identity. If I sign on site A and site B and site C my wallet is no longer anonymous.
> 
>     * At some point the regulation will get involved, I think in particular to the GDPR in Europe, the wallet identifier will be rightly considered as a personal data and all applications using it will be in trouble

I think there is a little misunderstanding, I'm talking here about a _decentralized_ application. 
- you should know what you are signing, unless you want to transfer all your coins to a stranger,
- it is the point of signing in to expose an identity so that you can be remembered bt the dApp. Now people use different accounts when they want to hide their identity across sites (cf Metamask where in one click you create another account for the same seed),
- all blockchains are using the wallet identifiers, they are in the ledger.

If you know other ways to sign to a dApp stored on Massa I'm happy to here about them :+1: 

Is the wallet plugin included in Thyra right now or does it require other installation steps ?

Can you guys write a little html/js frontend example with only a big "Connect" button that signs a message which is sent to the a smart contract backend and stored there ?

**Comment by SlnPons** [comment]
```it is the point of signing in to expose an identity so that you can be remembered by the dApp. Now people use different accounts when they want to hide their identity across sites (cf Metamask where in one click you create another account for the same seed),
all blockchains are using the wallet identifiers (addresses), they are in the ledger.```
Currently, I don't know a different way to sign up. But I would be VERY keen to think about another way to sign up that using your wallet. In real life, I don't sign up on platforms using my credit card and I would never do that. I think for mass-adoption this point is critical ...

`Is the wallet plugin included in Thyra right now or does it require other installation steps ?` 
Today, you need to install the plugin to Thyra. And it's a manual installation. [Here](https://github.com/massalabs/thyra-plugin-wallet/blob/main/README.md) here is the info to install it to Thyra. 
In (a very near) future, this plugin will be added by default to Thyra as we can consider it as a basic. But atm it needs further developments and security thus our choice to leave it out. (But to reassure you, Thyra has a wallet by default currently so users can use the website on-chain but it will be killed very soon thus my wish that you use the plugin rather than the Thyra's one).

```Can you guys write a little html/js frontend example with only a big "Connect" button that signs from Thyra a callSC of a little smart contract function which generates an output event like "Address XXX is connected" ?```
Indeed, we have some work to do to better document Thyra and its plugin usages. Now, we have an external user (🥳) we'll certainly do it soon.

**Comment by sebastien-forestier** [comment]
Thank you it's very clear. Waiting for a little example then ;) and honoured to be one of your users!

**Comment by SlnPons** [comment]
This issue will define the standard: https://github.com/massalabs/massa-standards/issues/13
And then the doc for Thyra's wallet will be updated and shared in this issue (and more broadly) to answer this question.

**Comment by SlnPons** [comment]
Issue solved thanks to the standard and MassaWallet plugin
