### ISSUE TITLE
Trouble uploading a website on testnet19

### ISSUE THREAD

**Issue by qdrn** [massalabs/thyra#482]
I have a hard time uploading a website (see discord for the zip) using thyra on testnet19. By the way I can't see any site on the registry. Is there an issue ?

Getting stuck on `Chunk upload 1 on 8`.

**Comment by qdrn** [comment]
![Screenshot 2023-02-17 at 14 37 08](https://user-images.githubusercontent.com/13425544/219667038-b7a7dfdf-b4ed-49e5-8ab1-fbb842bc696b.png)

**Comment by SlnPons** [comment]
On my side, when trying to upload the build.zip shared on Discord. I have the following error (see below). 
I can see that one chunk is uploaded but it gets stucked and no other are passing through so I have a timeout error. 

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/109611779/219685197-73ee3b72-26a4-4ecb-8ed0-66074de7e883.png">
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/109611779/219685538-74bc700a-dd08-4eec-b581-94dfb13b336a.png">

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/109611779/219685585-da322135-2334-4ae5-a8c3-394caa37075b.png">

**Comment by gregLibert** [comment]
@SlnPons your issue is describe here #483

**Comment by SlnPons** [comment]
Closing this issue as it's outdated now.
