### ISSUE TITLE
Missing architecture for MacOS Installer in releases

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/thyra#487]
**Describe the bug**
The architecture of the MacOS installer isn't specified for the MacOS installer in the releases.

**To Reproduce**
1. Go to https://github.com/massalabs/thyra/releases/tag/v0.1.9
2. See the assets list
3. Can't find the specific version for ARM64 or AMD64

**Expected behavior**
- Have 2 installers for MacOS: one for ARM64 and one for AMD64

**Thyra version**
v0.1.9

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
- This bug has been introduced by https://github.com/massalabs/thyra/pull/455
- The issue is that we do not name the binaries built by pyinstaller [here](https://github.com/massalabs/thyra/blob/5bcee617c54a506dbc4d0a96cec53c35253aaf06/.github/workflows/build.yml#L107)

**Comment by thomas-senechal** [comment]
I think we should add make sure all installers we produce follow the same naming convention. For example:
```
${binary_name}_${target}_${arch}
```
With:
- `target` being the targeted operating system: Windows, MacOS, Linux...
- `arch` being the targeted architecture: arm64, amd64...

So, we would have installers named such as `thyra-server` is named now:
```
- installer_darwin_arm64
- installer_darwin_amd64
- installer_windows_amd64
```

**Comment by SlnPons** [comment]
@thomas-senechal is it blocking thyra installation process in MacOS?

**Comment by thomas-senechal** [comment]
> @thomas-senechal is it blocking thyra installation process in MacOS?

Yes since the `macos-installer` can either be for `ARM64` or `AMD64`. We don't know which one it will be, it's fully random since it depends on which target job (by this, I mean either the `ARM64` or `AMD64` MacOS job) will end at last.

For example, the latest `macos-installer` ([here](https://github.com/massalabs/thyra/releases/tag/v0.1.9)) is for `AMD64`. So, as an `ARM64` MacOS user, I can't use it.

**Comment by SlnPons** [comment]
Ok, very clear. 
How can we coordinate on this point and the priorities please? Can we help?
Because we have a user test for the node-manager next week (blocked by this one https://github.com/massalabs/thyra/issues/476 too) so at minimum I need visibility on when it can be done and at best we can make it happened ;)

**Comment by thomas-senechal** [comment]
> Ok, very clear. How can we coordinate on this point and the priorities please? Can we help? Because we have a user test for the node-manager next week (blocked by this one #476 too) so at minimum I need visibility on when it can be done and at best we can make it happened ;)

Should be in review by the end of the day or tommorow morning !
I'm still working on #476, this issue is my next priority.
