### ISSUE TITLE
Plugin logo is not available when plugin is stopped

### ISSUE THREAD

**Issue by peterjah** [massalabs/thyra#496]
**The problem(s)**
Because the plugin logo is served by the plugin api, it is not available when plugin is installed but stopped.
Thus the plugin manager frontend is missing it.

**To Reproduce**
Stop a plugin

 **Possible solutions**
option 1:
Put the logo in the plugin zip file, alongside the plugin binary
option 2:
Use placeholder logo, if its not available
option 3:
Download the logo after the plugin register so it will be available

**Comment by SlnPons** [comment]
Is this will be solved with: https://github.com/massalabs/thyra/issues/550 @peterjah ?

**Comment by Pierregvx** [comment]
option 1 implemented via https://github.com/massalabs/thyra-plugin-hello-world/pull/15
