### ISSUE TITLE
`--version` always returns `main`

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/thyra#507]
**The problem(s)**

When starting `thyra-server` with the `--version`, Thyra displays `main` instead of the real version name.

**To Reproduce**

1. Install Thyra from the release page binaries
2. Run `thyra-server --version`

**Expected behavior(s)**

Displays the version number.

**Thyra version**

v.0.1.10

**Desktop:**
 - OS: MacOS, Linux, Windows
 
 **Any other useful info**

- It looks like the issue come from [this line](https://github.com/massalabs/thyra/blob/e7bf34b27e5045b78365e8b5f464a5ac920ba6bb/.github/workflows/build.yml#L66).

**Comment by thomas-senechal** [comment]
What's happening is that we run this workflow on the main branch, and so, the `${GITHUB_REF_NAME}` is set to `main` and not to the tag name of the version we are going to create. An easy fix is to just change:
> ~~run: echo -e "${GITHUB_REF_NAME}" > cmd/thyra-server/version.txt~~
```
run: echo -e "${{ inputs.tag_name }}" > cmd/thyra-server/version.txt
```

To use the right version.

**Comment by Pierregvx** [comment]
[It worked] ( https://github.com/massalabs/thyra/actions/runs/4871870716/jobs/8689361339). The issue is blocked by #629 to have a green ci (due to an update of the description of the wallet in the store)

**Comment by SlnPons** [comment]
@Pierregvx it doesn't work on my side. Let's catch up to test this together please.

**Comment by Pierregvx** [comment]
> @Pierregvx it doesn't work on my side. Let's catch up to test this together please.

on draft It only works for the server binary because the installer uses the latest release, we can talk about it during the sync

**Comment by Pierregvx** [comment]
reopening a pr with  the command
`go build -ldflags="-X 'main.Version=$VERSION'"`
to set the version
