### ISSUE TITLE
Install the wallet plugin at the same time as Thyra

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#511]
**Context**
This issue is part of the 1st milestone to achieve for the Thyra squad working on the wallet plugin. See [here](https://www.notion.so/massa-innoteam/Wallet-85ec39b64f72481f98a0ff31c8a5608e?pvs=4#b67bc640e5414b328b64fe475658f428) for all details.

The objective of this issue is to provide the wallet plugin by default to the user.

**User flow**
1. User goes on the installation.md
2. User download the appropriate installer based on their OS 
3. User double click on the downloaded installer, and the installation starts
4. At the end of the install, user sees the icon stay in their app menu
5. User starts thyra, user can see "Massa wallet" listed in the icon tray 
6. User clicks on "Massa wallet" in the list, user sees their favorite browser opening and the wallet page opened: my.massa/thyra/massalabs/wallet

**How to**

- [ ] Update & clean if necessary thyra installation script so the wallet plugin is installed by default
- [ ] Make sure it's working on all OS (use e2e test already existing)
- [ ] Update the icon tray menu to match the user flow description above - _nice-to-have_

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Test it using the user flow above

**Comment by peterjah** [comment]
this issue is mixing a lot of different things :/
- Install scripts on every os ,
- changes in the icon tray
- changes in api
- change the name of wallet plugin
should be splitted

**Comment by SlnPons** [comment]
@peterjah you're right. 
Here is what I suggest to do: 
* change the name of the wallet plugin: will be done in another ticket ( @Thykof can you add the ticket in question please?)
* change the icon tray: nice-to-have, I'll create a ticket in the right repo to address this issue and we'll see if it relevant to do it by then. 
* install script on all OS: needed I would like the wallet to be installed at the same time as thyra. After checking, it seems that we have an endpoint that allows us to install plugin that we could use.
* change in API: not sure I understand this point... maybe a quick talk about it would be needed.

**Comment by Thykof** [comment]
ticket for renaming the wallet: https://github.com/massalabs/thyra/issues/589

**Comment by gregLibert** [comment]
I prefer #604: it's not Thyra job to force the installation of the plugin when it starts.

This can imply weird side effects such as:
- If I don't want to use this wallet, I can't
- If something is wrong with this wallet install, we are blocking thyra (we already had a bug on that)

**Comment by SlnPons** [comment]
To test this issue I've made a new release: v0.1.14: https://github.com/massalabs/thyra/releases

There still is a couple of things that I don't find "normal" using Thyra installer on MacOS: 

* It installs the folder "my_plugins" that we removed from Thyra. See https://github.com/massalabs/thyra/issues/605
Expected: this folder is not created. Only "plugins" folder must be created.
* It installs the wallet plugin under the name "wallet-plugin_darwin-arm64"
Expected: the wallet plugin installed at the same time as Thyra should be the generic one and so follow the naming convention. It should be named: "wallet-plugin" in the "plugins" folder in "thyra"
* Even though the wallet plugin is installed (see above) it doesn't appear on the list of plugins in thyra home page nor thyra's plugin manager page
Expected: wallet plugin appears on the home page

Here is the terminal page I can see: 
<img width="848" alt="image" src="https://user-images.githubusercontent.com/109611779/232787066-343b9daa-1c21-484e-8bdb-5aefa9a558f0.png">

**Comment by Thykof** [comment]
> Even though the wallet plugin is installed (see above) it doesn't appear on the list of plugins in thyra home page nor thyra's plugin manager page
> Expected: wallet plugin appears on the home page

The same thing happens, to test it you need to download thyra server from your draft release in order to run the thyra-server you want to test, not the previous version installed by the installer

**Comment by SlnPons** [comment]
@Thykof As I said in my comment I am using the installer of the v0.1.14 and not the "latest" release. 
Do you mean that I should flag the v0.1.14 as "latest" so the installer uses the right version?

**Comment by Thykof** [comment]
@SlnPons I am saying that the installer of the v0.1.14 is installing the latest version of thyra (v0.1.13). So when you run thyra you run the version just installed by the installer v0.1.14. The installer v0.1.14 installs thyra-server v0.1.13. So, there are 2 options:
- 1: release v0.1.14 (as the latest, i.e. publish the draft)
- 2: download thyra-server v0.1.14 and run it, test, if everything is QA OK, you can release (option1)

keep in mind that we have 2 PR pending in review that will need to be release (part of milestone1):
- #633
- #634
