### ISSUE TITLE
thyra installation failed on ubuntu

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/thyra#520]
**The problem(s)**
I got this when I tried to run the thyra installer on ubuntu
```
sudo ./thyra-installer_linux_amd64
root        : INFO     Starting installation of thyra
root        : INFO     Creating config folder
root        : INFO     thyra-app downloaded successfully
root        : INFO     Thyra app installed successfully
root        : ERROR    Command failed with error : Failed to set capabilities on file `/usr/local/bin/thyra-server' (No such file or directory)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
```

**To Reproduce**
get the thyra installer here . https://github.com/massalabs/thyra/actions/runs/4365977185
unzip and run `chmod +x thyra-installer_linux_amd64`
run `sudo ./thyra-installer_linux_amd64`

**Expected behavior(s)**
normal installation
**Screenshots**

**Thyra version**
v0.1.10

**Desktop (please complete the following information):**
ubuntu 22.04 on qemu
 
 **Any other useful info**

**Comment by gregLibert** [comment]
Error is here :
 super().installThyraApp() 
We should install thyra server instead of thyra app before setting capabilities...
