### ISSUE TITLE
Re-design thyra home page

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#525]
**Context**
Following the UX/ UI designs to match them, let's redesign thyra page.

**User flow**
1. User installs thyra app using installer 
2. User sees thyra logo on the icon tray
3. User sees "Home" in the menu
4. User clicks on "Home" and a web browser page opens to: **https://my.massa/home/**
5. User sees the home page as deisgned

**How to**

- [ ] Reproduce design here: https://www.figma.com/file/EGOu3XvvTTNMug2tUbfEP3/THYRA?node-id=3%3A357&t=dxaY43i0glLivyzz-1
- [ ] While reproducing this design, if you notice that some functionalities / links are missing, please check with PM
- [ ] Normally: 2 plugins should appears on this page after installing: 
* Web on-chain: fake plugin as it's not pluggenised yet
* Wallet plugin: installed by default at the same time as Thyra

**Technical details**
Action plan to tackle this page needs to appear here so that we identified potential blockers.

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by 0xMazout** [comment]
Action Plan : 

- [ ] Update the design of Card Plugin component
- [ ] Update the background image
- [ ] Update the Massa Color Theme of Tailwind (Dark and Light)
- [ ] Install Twin.Macro  --> https://github.com/ben-rogerson/twin.macro ( This is to have a cleaner code and easy to read )
- [ ] Download the news logos from Figma
- [ ] Implement Dark Mode / Light Mode

**Comment by SlnPons** [comment]
@0xMazout check out the "how to" section, only 2 plugins are expected (for now) on the home page :) 
(hello world + node-manager will be listed as not installed on the plugin manager page - so not this issue) 
Let me know if it's not clear

**Comment by SlnPons** [comment]
@0xMazout don't bother with fake plugins. Web on-chain will be installed by default. 
* Registry is not a plugin and shouldn't be considered as one. I will discuss with @LucasF243 to make sure we can display this page differently but I want this page to be accessible as soon as thyra is installed without pretending it's a plugin. 
* Hello world is a real plugin, but it doesn't nothing so not sure it will appear on the list .... to be discussed with back-end dev to find a solution.

**Comment by 0xMazout** [comment]
The Code is in Code review but should only be tested when this will be merged 
https://github.com/massalabs/thyra/issues/545

**Comment by 0xMazout** [comment]
The code is working and tested .
But we have a problem on the CI 
I Tried to debug it but it doesn't work 
I'm not the skillest of the group to doing this kind of stuff

When someone will be free to help or to take the CI in charge this issue can be merged.

So now i focus on the plugin manager page

**Comment by SlnPons** [comment]
It's niceeee to see such a home page!!! :) :) 

@0xMazout how much time it takes to change the description of the plugins? 
Is there a way I can do it myself from the "store" repo that Pierre created so I don't bother you with this? 

Otherwise, some points to improved from a dev perspective to match the designs: 
1. Elements on the card aren't aligned (for instance the plugin name: it seems dependent of the plugin description length). All plugin names should be aligned, same for the descriptions etc... all elements must be at the same position on all cards so it's easy to read. 
![Image](https://user-images.githubusercontent.com/109611779/228271722-302f1e27-6fd1-4c46-bb8a-bf147da84f20.png)

2. The toggle for dark vs light theme is not consistent. It has 3 behaviours, it should have only 2. 


![Image](https://user-images.githubusercontent.com/109611779/228272251-925c2ba1-9c17-4fd2-9529-beeb3b55a018.png)



![Image](https://user-images.githubusercontent.com/109611779/228272330-90ad813c-dab9-4dd1-9084-b58af5f4a2e8.png)



![Image](https://user-images.githubusercontent.com/109611779/228272428-9b984dfa-8648-417e-8adf-cc87ffea7a3f.png)


3. How the plugins are ordered? I'm struggling to understand how it's ordered? by installation date? alphabetically?
4. The "hello world" plugin is changing position jumping from one to another (not sure it's very clear... but when you open the page, all plugins appear and the hello world plugin jumps before the node-manager then after, then before again... weirdo)
5. We need to address this issue to consider the page done: https://github.com/massalabs/thyra/issues/548 
note that the logos need to be squeezed / resized to be consistent with others! cc @LucasF243 

@0xMazout can you try to estimate the volume of work in days for the points mentioned above please?
As it's a "in-between" state, I don't want to invest too much time so depending on your evaluation we'll address them or not.


Some points to improve from a UX/UI perspective: 
Same for you @LucasF243 the point below are more opinions and things we should improve in the future, not sure we should spend time on them now. If you think otherwise, let's discuss. 
1. The title is way too big for 14'' screens. + The page is called "home" so it's a bit weird to see the word plugin in big like this. 
2. When in light mode (white colours) the logo that has white can't be seen. This should be improved as we can't force people to change or adapt their logo only for this store 
3. The "blue light" around the dark / light toggle takes too much attention. It's better without it.
4. The "manage plugin +" text should be smaller, same I find that it drags too much the attention
5. The designs should be optimised for specific screens size. I find it "not professional" to scroll down to see just more 2cm and same I can't see the block's border, I think I would have prefer more space at the bottom... 


![Image](https://user-images.githubusercontent.com/109611779/228276474-cb384fcc-2ebe-431b-97b8-dcc5458c9f42.png)



![Image](https://user-images.githubusercontent.com/109611779/228276574-49463d87-4438-43a9-9f96-101862a26396.png)

**Comment by 0xMazout** [comment]
Yes it's normal it was a side effect of a refactoring , and it's solve in the actual pr i'm working on it 

on both page plugin and home 👍
