### ISSUE TITLE
Secure Connection Failed 

### ISSUE THREAD

**Issue by Thykof** [massalabs/thyra#531]
**The problem(s)**

When I navigate to <https://my.massa/thyra/home> I have an error in the console and firefox doesn't show me the page.

**To Reproduce**

Run Thyra and go to <https://my.massa/thyra/home>.

**Expected behavior(s)**

I should see the thyra home page

**Screenshots**

![image](https://user-images.githubusercontent.com/11590067/224366984-7423b86c-9ed6-4089-942a-c472d60f3cfb.png)

error in the terminal:
```
while handling SNI Hello request: while loading CA certificate: while loading certificate file from /Users/nathanmassa/Library/Application Support/mkcert/rootCA.pem: stat /Users/nathanmassa/Library/Application Support/mkcert/rootCA.pem: no such file or directory2023/03/10 16:14:31 http: TLS handshake error from 127.0.0.1:61186: while handling SNI Hello request: while loading CA certificate: while loading certificate file from /Users/nathanmassa/Library/Application Support/mkcert/rootCA.pem: stat /Users/nathanmassa/Library/Application Support/mkcert/rootCA.pem: no such file or directory
2023/03/10 16:14:36 [GET /plugin-manager]
```

**Thyra version**
The version of Thyra the bug is present in.

**Desktop (please complete the following information):**
 - OS: MacOS amr
 - browser: firefox
 
 **Any other useful info**
Maybe I haven't gone through the new installation process.

**Comment by SlnPons** [comment]
@Thykof when you have time, could you test again with the latest version of thyra by installing it using the latest release please? It should solve your issue. 
https://github.com/massalabs/thyra/releases/tag/v0.1.11
It should solve your issue. 
Thyra is currently evolving a lot, with each testnet, and so it's best to keep it updated ;)

**Comment by Thykof** [comment]
I am blocked because I don't manage to run the installer, here is a new issue https://github.com/massalabs/thyra/issues/535

**Comment by thomas-senechal** [comment]
@Thykof Did you managed to make `https` work following my comment in #535  ?

**Comment by Thykof** [comment]
It works, I get redirected to http://my.massa/thyra/home/index.html
