### ISSUE TITLE
command thyra-server crash 

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/thyra#538]
**The problem(s)**
`thyra-server` returns :
```
2023/03/14 15:22:56 Connected to node server https://test.massa.net/api/v2 (version TEST.20.1)
2023/03/14 15:22:56 Plugin Manager initialization
2023/03/14 15:22:56 reading config directory '': Unable to read config dir: /home/massa/.config/thyra: stat /home/massa/.config/thyra: no such file or directory
```
**To Reproduce**
1. download thyra installer and launch it 
2. run `thyra-server`

**Expected behavior(s)**
run the server
**Screenshots**

**Thyra version**
v0.1.11

**Desktop (please complete the following information):**
ubuntu 22.04 on qemu vm

**Comment by thomas-senechal** [comment]
Closing since it's related to https://github.com/massalabs/thyra/issues/523
