### ISSUE TITLE
Enable routing of nested subdirectory with frontend on Thyra

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/thyra#555]
**Context**
When we build frontend we need to access to files in subdirectory 

Currently we just have access to the first level. And we need dynamic depth 

**How to**
Upgrade the process for Thyra in discovering nested folders

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Create a folder 
Containing index.html , make a link to file /test/test.js
Create a file test.js 
Try to access to the index.html file and see if you have errors 
(Devs on it should provide an easy way to test it with previous projects)

**Comment by SlnPons** [comment]
Hey @mazmassa @gregLibert do we still need to address this task at some point or with the new way of building front-end this is solved? 
Sorry for the naive question... and thank you guys :)

**Comment by mazmassa** [comment]
> Hey @mazmassa @gregLibert do we still need to address this task at some point or with the new way of building front-end this is solved? Sorry for the naive question... and thank you guys :)

This is already implemented! All good!
