### ISSUE TITLE
Delete and Re-install a plugin is not working on windows

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/thyra#557]
https://user-images.githubusercontent.com/10938862/227912769-1e73cc2d-073c-462d-88ca-32d6fc322b1a.mp4

We have to delete the file manually to re-install the plugin 

Context
On Plugin Manager when you delete a plugin and you re-install it . The folder is not deleted in 

![Image](https://user-images.githubusercontent.com/10938862/227913337-9a797f24-a820-45e8-81d4-457edab2b805.png)

How to
Force the delete of the file on backend side

Technical details
Give the technical insights so anyone in the team can tackle the tasks - Dev

QA testing
Delete a plugin, 
use the install plugin block and re-install it

**Comment by 0xMazout** [comment]
When i was testing this 



![Image](https://user-images.githubusercontent.com/10938862/228258263-4ea968c5-ce28-433a-b0dd-462e3d5db350.png)

**Comment by 0xMazout** [comment]
And if i want to install it using the store 

![Image](https://user-images.githubusercontent.com/10938862/228258530-610c7fb2-c250-4476-b7ff-5e2dec9b9191.png)

**Comment by SebastienValla** [comment]
it is not because of insufficient permissions

**Comment by SlnPons** [comment]
@LucasF243 do you have thyra installed now? 
Could you QA this ticket for me please?

**Comment by LucasF243** [comment]
Yes no problem, I have thyra on my computer

**Comment by LucasF243** [comment]
QA validated
