### ISSUE TITLE
Add missing endpoints to the Postman collection

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/thyra#558]
**Context**
Some endpoints are missing from the Postman collection. We need to make sure every endpoints are available as Postman collections to allow us to use our endpoints easily with Postman.

**User flow**
No user flow since it's a purely development oriented task

**How to**

- [ ] List the parts of Thyra that doesn't have a Postman collection
- [ ] Add missing endpoints to the Postman collection

**Technical details**

- Make sure to make collection use simple

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by amanx123** [comment]
I would like to work on it. Assign me please

**Comment by SlnPons** [comment]
Hi @amanx123!! Of course, are you familiar with swagger and postman?

**Comment by gregLibert** [comment]
As we are using robot framework for the test, it's useless to maintain a postman collection if everything is fine with the swagger specification.
@thomas-senechal can you:
- create an issue to remove postman
- create an issue to document how to use postman with the swagger spec

**Comment by thomas-senechal** [comment]
> @thomas-senechal can you:
> 
> * create an issue to remove postman
> * create an issue to document how to use postman with the swagger spec

Done : 
- https://github.com/massalabs/thyra/issues/741
- https://github.com/massalabs/thyra/issues/742

**Comment by SlnPons** [comment]
@Pierregvx please see above. You wanted to update postman collection, I don't think it's relevant. 
Maybe we should consider addressing these 2 issues instead.
