### ISSUE TITLE
Thyra Plugin Manager API , is switching order of plugins

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/thyra#565]
**Context**
The plugin Manager API is sending objects containing datas of plugins
For the frontend we refresh this periodically (10 secs) but sometimes the plugins order is changing without any action from frontend

Example : Hello World first
![Image](https://user-images.githubusercontent.com/10938862/228467824-69bb4699-e181-45cb-9f61-9560e0960c49.png)

Node Manager first
![Image](https://user-images.githubusercontent.com/10938862/228468239-1bbf7f15-0fbc-4506-9d1a-5102e74a2daf.png)

This cause a switch on the frontend because we base the position of the plugins on their coming order

**How to**
Solve this problem on API side

Or 

Order by alphabetic name and rework on the frontend to have a first List of fake plugins not ordered, then push another list ordered by alphabetic

**Technical details**
See How To

**QA testing**
Observ the frontend if on 5 minute you can't see any switch on plugin position it's working

**Comment by SlnPons** [comment]
@0xMazout I think you address this ticket into another PR, is that correct? 
If so, can you link the PR in question and close this ticket please? 
Thanks a lot :)

**Comment by 0xMazout** [comment]
Yes it's correct on this issue : https://github.com/massalabs/thyra/issues/569
