### ISSUE TITLE
Windows 11 installer not working

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#567]
**The problem(s)**
Following the steps on the installation.md, the windows installer is not working. 

**To Reproduce**

1. Go on the last release
2. Download installer.exe
3. Open it as an admin (important note: this is not normal to ask users to do such a manip: you should just click on it!!! to be improved asap) 
4. The script run and all a sudden stops
5. Thyra is not installation
6. See logs attached for more details

**Expected behavior(s)**
User can download the installer and installer thyra without doing anything special.

**Thyra version**
v0.1.11

**Desktop (please complete the following information):**
 - OS: windows 11
 
 **Any other useful info**
[thyra_installer.log](https://github.com/massalabs/thyra/files/11099764/thyra_installer.log)

**Comment by SlnPons** [comment]
cc @LucasF243 experienced this bug and can help you to reproduce if necesary.

**Comment by thomas-senechal** [comment]
We should catch exceptions somewhere to avoid missing errors.

**Comment by Pierregvx** [comment]
I just added windows and got it too

**Comment by Pierregvx** [comment]
windows detected a virus but then it worked well when I disabled the security and launched it.
