### ISSUE TITLE
Rework HomePage And Plugin Manager Page card

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/thyra#569]
Context

Rework on the HomePage and Plugin Manager Page

There is the list of things to do 

- [x] Align Content on Card
- [x]  https://github.com/massalabs/thyra/issues/548
- [ ] Suppress the blue light on focus (optional)
- [x] Regex on Name Plugin with Major Caps and Small Caps to avoid duplicate

**Comment by 0xMazout** [comment]
Small Rework on Homepage to Harmonize the look with the other page

**Comment by 0xMazout** [comment]
As requested : 

Add a spinner like on download to display to users the download is pending

**Comment by SlnPons** [comment]
putaaaaaiiiin c'est tres propre ce petit travail sur le bloc d'install !!!! Je kiff!

**Comment by SlnPons** [comment]
However, little sth: On the plugin manager page
When you: 
* Use the install bloc and copy/paste an address
* the plugin appears on the store list (super cool effect!) 
* you can download the plugin to add it to your plugin list
* you can't delete it to install a now version .... 
* you can't install 2 plugins with the same name (which is a good behaviour) 

--> but in fine: user can't access new released version.

@0xMazout @Pierregvx I recommand you to play with this part of the front-end to detect things we can / should improve on the plugin manager ;) 

Here I see at least 3: 
- update of the plugins in the store
- update of the plugins installed 
- automatically add plugin listed on the plugin store list on the plugin store front-end (it seems that it's not the case here - eg: node-manager)
- (add automatic tests or sth like this to detect discrepencies between the 2 lists: here the node-manager logo is different from one list to the other). 

Please react to this message to let me know that you're aware of this, and we'll add these tasks in our milestones ;)

**Comment by SlnPons** [comment]
Guyyys @0xMazout @Pierregvx the user flow described above isn't correct!! I was experiencing this because the release wasn't published and so the .zip wasn't recognised. 

I think the points of improvement still make sense BUT nothing is urgent as we're currently handling gently this :) 
Very well done Lucas & Pierre (I guess) who worked on this part, it's nice :)
