### ISSUE TITLE
Update plugin URL

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#589]
**Context**
All plugins should follow the same naming convention.
This convention is: my.massa/thyra/plugin/author-name/pluginname

**How to**

- [ ] Update plugin URL everything it is needed
- [ ] https://github.com/massalabs/thyra-plugin-wallet/pull/78

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
- Open Thyra home page
- see that wallet plugin name is "Wallet Plugin"
- click to open the wallet plugin
- see that the URL is http://my.massa/thyra/plugin/massalabs/wallet/web/index.html
- non-reg: see that web-on-chain page are still available
- non-reg: see that node manager plugin still works

**Comment by Thykof** [comment]
> @Thykof I would like the plugin to follow the naming convention for all the plugins (internal or external) my.massa/thyra/authorsName/pluginName
> 
> So no space, no dash in URLs. Also, we shouldn't force http, never. It's not standard.

Okay thanks so I transfert this issue to Thyra repo.

I will use this lib https://github.com/iancoleman/strcase to format the plugin author and plugin name in the URL on Thyra side so that any plugin will have the same URL format

**Comment by Thykof** [comment]
After discussion with @SlnPons we will keep prefix url /thyra/plugin and we will slugify plugin author and name 

http://my.massa/thyra/plugin/Massalabs/Massa-Wallet/web/index.html

in addition, we will rename massa wallet into wallet

**Comment by SlnPons** [comment]
Niceeee!!

**Comment by mazmassa** [comment]
> @Pierregvx @0xMazout @mazmassa please read and ack this change in thyra plugin manager as you will build on top of it 

The MR is **CLOSED**. Is that yet a valid question for us @SlnPons !?

**Comment by Thykof** [comment]
> > @Pierregvx @0xMazout @mazmassa please read and ack this change in thyra plugin manager as you will build on top of it
> 
> The MR is **CLOSED**. Is that yet a valid question for us @SlnPons !?

No change required in node manager side
