### ISSUE TITLE
https://my.massa/thyra/home/ not working on chromium ubuntu

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#597]
**The problem(s)**
<img width="869" alt="image" src="https://user-images.githubusercontent.com/109611779/230560727-7738b7d3-34da-429e-a4ac-168a96e02b10.png">

**To Reproduce**
Use the same browser and OS that this user

**Expected behavior(s)**
https should work 

**Screenshots**
[Screencast_from_06-04-2023_222700.webm](https://user-images.githubusercontent.com/109611779/230560679-af83e37b-44b0-42d4-91b9-31f5f5151ad2.webm)

**Thyra version**
Latest release.

**Desktop (please complete the following information):**
 - OS: Linux ubuntu

**Comment by Pierregvx** [comment]
I could not reproduce this issue, I didn't have any problem connecting on https both on my host and my ubuntu vm

**Comment by thomas-senechal** [comment]
@SlnPons Could you ask for his installer logs? It could help us to know if something went wrong with certifcates generation

**Comment by SlnPons** [comment]
@thomas-senechal is this enough `this is the warning btw 2023/04/06 22:27:32 http: TLS handshake error from 127.0.0.1:56370: remote error: tls: unknown certificate`

**Comment by SlnPons** [comment]
[thyra_installer.log](https://github.com/massalabs/thyra/files/11179952/thyra_installer.log)

here you are guys

**Comment by Pierregvx** [comment]
@thomas-senechal could it be because he used sudo ?

**Comment by Pierregvx** [comment]
the error occured because he double clicked on the installer to launch it

**Comment by Pierregvx** [comment]
a part of the program require to enter a password but it cannot be entered because there is no terminal to read the password from.
 the installation crashes after the install of thyra but before the creation of the certificate. This is why he got this error

**Comment by SlnPons** [comment]
Closing this issue as we can't reproduce and thyra changed a lot. So I'll contact you directly to test on the new version that you can access it now :) 
Thanks again for contributing to a better Thyra 🚀 ❤️
