### ISSUE TITLE
Add repo structure explanation

### ISSUE THREAD

**Issue by gregLibert** [massalabs/thyra#6]
We should explain how the code is organized to make it easier to new devs.

**Comment by SlnPons** [comment]
@SebastienValla @Trottoir @ASAPSegfault is this issue still relevant? 
Wondering if we should address it quickly as (1) the team grows, (2?) when we will demo the product to the community they will be able to access our GitHub repository.

**Comment by SlnPons** [comment]
Hey @gregLibert @peterjah do you think we should do this before mainnet?
My understanding was that this issue was to improve how our code is set-up and organise, as we plan to open thyra code to external people with the mainnet, should we try to do it?
