### ISSUE TITLE
[investigation] Identify "installer" standards on the market

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#619]
**Context**
This issue is part of the mainnet plan for thyra / massastation. 
All details can be found [here](https://www.notion.so/massa-innoteam/Perfect-end-to-end-user-flow-3603a6f74a274850907a41ab1f361c82?pvs=4#0fcd4cc1c2bb437d98df1947750af0a0)

--> the objective of this issue is to identify the market standard regarding the different installer that exist on the different OS listed on the [DoD](https://www.notion.so/massa-innoteam/Plan-for-the-mainnet-c574da44a4854eb3841a5f2e93a2977c?pvs=4#e7db6fa53fa84264954075011432ce70)

**How to**

- [ ] Dedicate time to review and analyse existing solutions
- [ ] Share findings and important info with the rest of the team

**Technical details**
To be added

**QA testing**
We know how other apps works and we understand the potential limitations for our needs.

**Comment by thomas-senechal** [comment]
Already done
We will go with Wails for now !
