### ISSUE TITLE
[investigation] Use wails to install MassaStation on MacOS

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#620]
**Context**
This issue is part of the mainnet plan for thyra / massastation.
All details can be found [here](https://www.notion.so/massa-innoteam/Perfect-end-to-end-user-flow-3603a6f74a274850907a41ab1f361c82?pvs=4#0fcd4cc1c2bb437d98df1947750af0a0)

--> the objective of this issue is to try to install MassaStation using Wails and to identify potential limits specifically on MacOS. 

**User flow**

Follow this high level user flow: https://www.figma.com/file/z5ekq4eP0YlLMDbgBCQqwb/Massastation-install?node-id=0-1&t=t4XV2PfDxjDAHnGu-0

**How to**

- [ ] Install wails 
- [ ] Embed and / or modify current binary to use it with Wails on windows
Test the following: 
* Compile
* Install
* Launch
* Icon tray 
- [ ] Make sure that it matches the user flow describe above (install thyra-server & thyra-app)

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Follow user flow above (Lucas Foucher to test as he has windows)

**Comment by thomas-senechal** [comment]
Closing.
We won't use Wails in the installation process since it doesn't allow us to perform `sudo` actions.
