### ISSUE TITLE
Delete register / Update process to load data from manifest in Information Struct

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/thyra#629]
## Context
We want some informations to fa accessible when the plugin is off.
To to that Some informations are directly accessible in the manifest of the pluginand can be extracted from it 
The register endpoint only needs to have the url as a parameter so it can connect the plugin with the right port

**Comment by 0xMazout** [comment]
Step 1 : Update this struct
![image](https://user-images.githubusercontent.com/10938862/232007853-5219ed11-13e5-4370-be9c-069803077876.png)

Step 2 : Update Swagger to add version  
![image](https://user-images.githubusercontent.com/10938862/232008528-9d8a695b-8bce-4f20-93d6-eabc6f865ee0.png)

Step 3 : Delete register if fully unused
![image](https://user-images.githubusercontent.com/10938862/232007964-8ce4742e-be29-4f04-aba0-86c3c567ca2a.png)

**Comment by SlnPons** [comment]
Blocked by: https://github.com/massalabs/thyra-node-manager-plugin/issues/43

**Comment by SlnPons** [comment]
@Pierregvx fyi - I think that this issue is now unblocked. Can you confirm?
If you agree, let's put it back in To do (or other more appropriate column ;) )

**Comment by Pierregvx** [comment]
blocked by https://github.com/massalabs/thyra-plugin-store/compare/main...6-fill-the-updated-pluginsjson-with-the-new-standard 
(  for the ci to be green )
