### ISSUE TITLE
system error when running binaries after download

### ISSUE THREAD

**Issue by jricho253** [massalabs/thyra#639]
Hi all, I keep getting these errors when trying to run the binaries I downloaded. How can i fix this please? Thank you 
![Uploading IMG_4379.JPG…]()

**Comment by SlnPons** [comment]
Hey @jricho253 could you try to give us more context please? Please use the bug template that exists to report your issue.

**Comment by SlnPons** [comment]
Closing this issue as I don't have any answer. But please @jricho253 feel free to re-open it when you have time to specify a bit more your problem :) 
Thanks!
