### ISSUE TITLE
[BACK] - Ask wallet password outside of HTML interface - Decrypt secret key with password

### ISSUE THREAD

**Issue by Trottoir** [massalabs/thyra#64]
For security purpose, find a solution to remove the password asking from the web brower.

In order to do that we need to create an heavy client that'll ask in a window the wallet's password.

Need to have a look on the [go-fltk](https://github.com/pwiecz/go-fltk/tree/main) solution

**Comment by SlnPons** [comment]
https://github.com/massalabs/thyra/issues/83#issuecomment-1249206458

**Comment by SlnPons** [comment]
#75

**Comment by SlnPons** [comment]
@Trottoir I think we can close this issue now. Do you agree?

**Comment by Trottoir** [comment]
I do agree, this has been done in an other issue by @Thykof
