### ISSUE TITLE
Update CI to build new installers

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/thyra#675]
**Context**
The new installer has been moved to this repository. We now need to update the CI to build the new installer instead of the previous one.

**How to**
- At each push, the installer must be built to ensure it's still built
- When we do a release, the installer must be added to the assets
- Replace the binaries with `massastation` binary following https://github.com/massalabs/thyra/pull/671

**Technical details**
- [x] The installer must be built as done [here](https://github.com/massalabs/MassaStation-Installer/blob/main/.github/workflows/package.yml)
    - [x] Windows https://github.com/massalabs/thyra/pull/681
    - [x] MacOS https://github.com/massalabs/thyra/pull/683
    - [x] Linux https://github.com/massalabs/thyra/pull/691
- [x] Update installer build scripts to use `massastation` instead of `thyra-server` and icon tray:
    - [x] Windows  https://github.com/massalabs/thyra/pull/678
    - [x] MacOS https://github.com/massalabs/thyra/pull/679
    - [x] Linux https://github.com/massalabs/thyra/pull/680
- [x] The binaries built by the scripts must be replaced by a `download_artifacts` action to avoid building massastation multiple times
- [x] The `thyra-app` binary must be removed from package since it has been merged into `massastation` (see https://github.com/massalabs/thyra/pull/671) https://github.com/massalabs/thyra/pull/677

**QA testing**
1. Check that the installers are available as artefact on `main` branch (once merged, otherwise, check the latest CI)
2. Download the installer for your OS (`.msi` = Windows, `.pkg` = MacOS, `.deb` = Linux)
3. Run the installer to install MassaStation
4. Run MassaStation (should be in your `/Application` on MacOS, your Start Menu on Windows, your Applications menu on Linux)
5. As a PM:
5.a. Do a release
5.b. Check that the installer has been correctly uploaded as assets

**Comment by SlnPons** [comment]
@thomas-senechal I just tested the arm.pkg from this draft release: https://github.com/massalabs/thyra/releases/tag/untagged-2c1256970186c99db423

- The installation is smooth and working well!! - well done 
- When I go on the list of app, I can see MassaStation (beautifuuuuuul), BUT I can't open it. See error below: 
<img width="845" alt="image" src="https://github.com/massalabs/thyra/assets/109611779/70ca3489-0e15-4276-b9b8-e46477eba71a">
