### ISSUE TITLE
[FRONT] - Error message - Display website naming rules

### ISSUE THREAD

**Issue by Trottoir** [massalabs/thyra#68]
Display an error message on validation of the DNS Name if the format input is correct.

DNS need to allow ONLY : 
- lower case letter
- numbers

**Comment by SlnPons** [comment]
@SebastienValla this issue can be closed, isn't it? 
Could you linked the related PR so we can track this later please? cheers

**Comment by SebastienValla** [comment]
> @SebastienValla this issue can be closed, isn't it? Could you linked the related PR so we can track this later please? cheers

Yes it is, it has been done on PR 84 as well,
https://github.com/massalabs/thyra/pull/106
