### ISSUE TITLE
Move from my.massa to station.massa

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#693]
**Context**
For the mainnet, we'll update the URL of MassaStation to make is more consistent with the global mkt strategy. This is why we'll move from "my.massa" to "station.massa". 

This objective of this ticket is to update every part of the code and including the interceptor to make this possible.

**User flow**

- my.massa/thyra/home --> station.massa/home 
If needed I can specify other pages changes. Please ping me as URL will change with redesigned :)

- https://station.massa/thyra/websiteCreator/index.html --> station.massa/websiteUploader/
- https://station.massa/thyra/plugin/massalabs/wallet/ --> station.massa/plugin/massalabs/wallet
- https://station.massa/thyra/plugin/massalabs/node-manager/  --> station.massa/plugin/massalabs/node-manager/
- https://station.massa/thyra/plugin/massalabs/hello-world/ -> station.massa/plugin/massalabs/hello-world/
- https://station.massa/thyra/registry/index.html -> station.massa/search/

**How to**

- [x] Update (refacto and/or improve) the interceptor
- [x] Update the code (check all part of the code where my.massa could be hard coded)
- [x] Update Web on Chain
- [x] Update thyra-plugin-wallet
- [x] Update Hello-World plugin
- [ ] Update node manager plugin

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

- [ ] #725  PR for changing host: my.massa -> station.massa
- [ ] #726  PR for changing URL path

**QA testing**
Try to open:

- http://station.massa
- http://station.massa/home
- http://station.massa/websiteUploader
- http://station.massa/search
- http://station.massa/plugin/massalabs/wallet
- http://station.massa/store

**Comment by SlnPons** [comment]
@B-Naoufal @peterjah I updated and suggested new URLs. 
For the plugins, I kept the current standard which is: */plugin/authorname/nameoftheplugin/web/index --> the /web/index are present for each plugin but I won't be able to explain the logic associated.... Pierre I let you add details about this if Naoufal needs them :) 

For the non-plugin pages, I used the re-design to suggest names: 
websiteCreators --> websiteUploader before after all you don't create anything you just upload a website...
registry --> search (into the Massa ecosystem) because I hope that soon enough we'll be able to add a search bar in this page and so search *.massa 

Feel free to challenge ;)

**Comment by Thykof** [comment]
we need to publish a release of the node manager plugin: here is the draft https://github.com/massalabs/thyra-node-manager-plugin/releases/tag/untagged-2411b2fe53ff6c57b79c

and also update the plugin store

PRs #726 and #725 are ready to merge
