### ISSUE TITLE
use x-nullable

### ISSUE THREAD

**Issue by gregLibert** [massalabs/thyra#74]
Use [x-nullable](https://goswagger.io/use/models/schemas.html#custom-extensions): false to avoid having a pointer for required fields.

**Comment by SlnPons** [comment]
@gregLibert I'm not sure that I understand what is a "pointer" in this context. Could you add more details about this issue so I can prioritise it ?

**Comment by gregLibert** [comment]
@SlnPons this is a technical vocabulary directly linked with how the memory is used.
It's not a high priority I think as it will only improve code readability a little bit.
I saw some PR already correcting this, so maybe not as important as initially expected.
