### ISSUE TITLE
Add My Station section in the front-end

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/thyra#759]

**Comment by SlnPons** [comment]
Hey, I noticed to minors changes to do: 
1. The behaviour of the "light / dark" mode is weird. See video
2. The sentence when "My Station" section is empty should be: 
"Browse the store below and manage plugins you've installed in this section" (missing a S at plugins ;))  the rules is singular: plug-in, plurial: plugins - it's weird I know but it's english haha)

**Comment by SlnPons** [comment]
After testing this front-end, there is a couple of things to change: 

1. The text when the section is empty is too bold / same font size as the text, at least it seems too. 
We should remove bold (if there is any - also it looks like there is bold on dark theme but not on light one... it's weird) and reduce the font size
Happy to do that online with you if needed. 


![Image](https://github.com/massalabs/station/assets/109611779/aa156499-00cb-4941-a33e-976cac884199)



![Image](https://github.com/massalabs/station/assets/109611779/fb57435b-abc9-477d-99c4-fe15f99d0fae)



2. There is a ";" in the section when there is no plug-in that needs to be removed


![Image](https://github.com/massalabs/station/assets/109611779/bb5f8182-4dfb-484e-99bb-4a657cac7070)

**Comment by SlnPons** [comment]
QA de la partie BE de "My Station": 

* Logo manquant
* Lorsque je clique sur la fleche pour ouvrir un plugin, le lien est cassé: cf screenshot pour le wallet. Si je refresh j'accède au wallet.
* Lorsque je clique sur la fleche, un nouvel onglet doit s'ouvrir car il faut que Massa Station reste ouvert. 


![Image](https://github.com/massalabs/station/assets/109611779/63640c48-d4f8-4842-8415-2a0c0b6ec064)

**Comment by pivilartisant** [comment]
i think @Pierregvx is in charge of this

**Comment by Pierregvx** [comment]
> i think @Pierregvx is in charge of this
> 

If you are mentioning the link yes  it should be good now
