### ISSUE TITLE
[ARCHI] - Deploy massa V15.1 on Innonet

### ISSUE THREAD

**Issue by Trottoir** [massalabs/thyra#80]
On the distant machine INNONET :

- [ ] - Pull right version of V15.1 massa-noe
- [ ] While doing this update, please list precisely ALL the changes, conflicts, problems that it causes with Thyra, web on-chain and playground products so that we can discuss them all together.
- [ ] - build with `cargo run build --features sandbox` 
- [ ] - Retrieve build in `/target` and depose it in a new folder in `massa-binaries`
- [ ] - Put configs in the new created folder, don't forget to change the port in the configuration in order to don't take one already taken.
- [ ] - Update Apache configuration
- [ ] - Update HTML of [https://inno.massa.net/](https://inno.massa.net/)
- [ ] - Ping PM to push a new release to update binaries for end-users
- [ ] - Update the existing documentation for our partners to use new InnoNet https://www.notion.so/massa-innoteam/How-to-Use-Massa-InnoNet-f8798bf8499e4f988d0610742d7b91de

**Comment by ASAPSegfault** [comment]
You can find the new procedure in details [here](https://www.notion.so/massa-innoteam/DevOps-45b18089672744ca8b03cafbffa14093)

**Comment by SebastienValla** [comment]
It is clear, ok.
