### ISSUE TITLE
[BACK/SC] - Change upload chunk logic

### ISSUE THREAD

**Issue by Trottoir** [massalabs/thyra#81]
**AS IS :** 

- We upload the first chunk with `initializeWebsite` in the dataEntry `massa_web` key of the `websiteCreator` contract
- Then for each following chunks, we append  in the dataEntry `massa_web` key of the `websiteCreator` contract with `appendBytesToWebsite`
- Between each chunks, we are waiting for an event to assert that the chunk uploading has ended
**TO BE :** 
- Upload each chunk with a new paramater in the smart-contract @Json struct => add an offset
- Upload each chunk with the key : ,  (...) following the chunkId
ex : 
	dataEntry "massa_web0" => chunk 0 : { data : "XXXX", offset : 0 }
	dataEntry "massa_web1" => chunk 1 : { data : "XXXX", offset : 260000 }
	dataEntry "massa_web2" => chunk 2 : { data : "XXXX", offset : 520000 }

**Comment by gregLibert** [comment]
@Trottoir Don't you think that:
- you will need the total size of the data to reserve it in the smart contrat ?
You can avoid that by extending before/after the first/last element of the byte array, but I think the code will be complicated.
- this mechanism should be implemented at a storage level ?
We are working right now on website, but we could image using that for storing other data.
- to follow chuck processing we will need an event manager ?
This event manager could also expose API for third-party applications, extension event triggering mechanism to the outside world of the node.
- all the chunks could be sent in parallel with a retry mechanism (to be linked with the expiry).

**Comment by Trottoir** [comment]
- We don't need the total data size as we are not registering everything in one key anymore `massa_web` => [massa_0, `massa_1 `... `massa_n`]
 This is also linked to this Issue [https://github.com/massalabs/thyra/issues/82](https://github.com/massalabs/thyra/issues/82)
- Totally, for me it's more than a website uploader, it's a "Blockchain data storage", as you explain we can register everything we want through this method and we'll be able to restitute the zip file to the user instead of rendering it as a webite for instance.
- We don't need that kind of feature to monitor that, for now we are registering a key `actual_chunk` & a `total_chunks` in the SC storage to determine the uploading status. 
**But in fact** we definetly need an event listener system that can be customizable & so on.
- Are you sure parrallel thread is usefull as we can only use the `CallFunction` that returns an operation id in all cases ? 
   I do agree about the retry mechanism

**Comment by gregLibert** [comment]
> We don't need that kind of feature to monitor that, for now we are registering a key actual_chunk & a total_chunks in the SC storage to determine the uploading status.

Having Thyra exposing selected events to local applications through its API, we can kill two birds with one stone:
- offering events to anyone (browser but also other local applications that can interact with Thyra)
- create a code sample showing how to consume events from deployer website

This need to be discussed with the PM and especially @SlnPons but bridging blockchain events to local applications can be huge :-)

**Comment by gregLibert** [comment]
> Are you sure parrallel thread is usefull as we can only use the CallFunctio

Let's talk about that tomorrow.

**Comment by ASAPSegfault** [comment]
Solution décidée : 
- Création d'une seule paire clé valeur avec padding du bytesArray avec des zéro
- Réception des chunks 1 à 1 et ajout dans le bytesArray au bon endroit, remplaçant le padding

**Comment by SebastienValla** [comment]
after some issues with last solution elected, we came back on the first solution proposed by Trottoir
