### ISSUE TITLE
[BACK] - Change Fetching Logic 

### ISSUE THREAD

**Issue by Trottoir** [massalabs/thyra#82]
AS IS : 
- Thyra retrives the zip website content in the dataEntry `massa_web` key in the `websiteCreator` contract

TO BE : 
- Thyra queries dataEntries "massa_web0", "massa_web1", "massa_web2" ... and append all chunks on resolving.

**Comment by gregLibert** [comment]
Is doing that means that we will need to do n calls to the node public API ?
In that case, website retrieval will be slower and less environmentally friendly, don't you think ?

**Comment by gregLibert** [comment]
This choice will impact the ability to store multiple websites at the same address.
But I'm not sure having multiple websites at the same address is an killer feature...

**Comment by Trottoir** [comment]
> Is doing that means that we will need to do n calls to the node public API ? In that case, website retrieval will be slower and less environmentally friendly, don't you think ?
- As the `getDataStoreEntries` RPC call accept an array of key and returns an array of values, 1 call is enough I think

> This choice will impact the ability to store multiple websites at the same address. But I'm not sure having multiple websites at the same address is an killer feature...
- Good remark, we can tackle that by changing keys to [massa_web_0_0 ... massa_web_0_n ] ...  [massa_web_n_0 ... massa_web_n_n ]

**Comment by gregLibert** [comment]
Using multiple keys also have an impact on storage, and therefore on the price that the user will need to pay.
This scenario implies (n-1)*size_of_storage_key additional bytes.

We also should discuss about potential performance differences when reading the data at the node level with core team.

**Comment by SlnPons** [comment]
Indeed so i'll close this issue as these 2 new ones are summarising the work to do: 
https://github.com/massalabs/thyra/issues/281
https://github.com/massalabs/thyra/issues/278

thanks for the rising it!
