### ISSUE TITLE
[FRONT] -Create My Websites pages

### ISSUE THREAD

**Issue by Trottoir** [massalabs/thyra#91]
Create a separate page & url for the website list table

check the UI here [https://miro.com/app/board/uXjVOhqpH6I=/](https://miro.com/app/board/uXjVOhqpH6I=/)

**Comment by Trottoir** [comment]
2

**Comment by SlnPons** [comment]
@Trottoir shouldn't we close this issue now?

**Comment by Trottoir** [comment]
Yeah I think that the registry one replaced that one
