### ISSUE TITLE
[FRONT] on website page, forbid to upload other thing than ZIP

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/thyra#99]
As Is 
All files are accepted in the website upload form
to be 
error message when trying to upload other file than .zip

**Comment by SlnPons** [comment]
@SebastienValla I think this task is closed, isn't it? 
Could you link the related PR please? Not sure why it's not already linked :/

**Comment by SebastienValla** [comment]
> 

Yes it is, it has been done on PR 84
https://github.com/massalabs/thyra/pull/106
